### ISSUE TITLE
NeoForge 1.21.1 ReforgedPlay + Traveler's Backpack crash

### ISSUE THREAD

**Issue by DaemonDeathAngel** [Tiviacz1337/Travelers-Backpack#1079]
1. Describe the bug 
Using the most recent version of the mod on NeoForge 1.21.1-21.1.83 and ReforgedPlay(ReplayMod) I recieve and error when attempting to change dimensions within the mod, the error being thrown had to do with Traveler's Backpack

2. Log
<details><html>
<body>

[05Dec2024 16:19:49.705] [Render thread/ERROR] [net.neoforged.neoforge.network.handlers.ClientPayloadHandler/]: Failed to handle advanced open screen from server.
--
5042 | java.lang.NullPointerException: Cannot invoke "com.tiviacz.travelersbackpack.inventory.BackpackWrapper.tanksVisible()" because "this.wrapper" is null
5043 | at TRANSFORMER/travelersbackpack@10.1.6/com.tiviacz.travelersbackpack.inventory.menu.BackpackBaseMenu.addSlots(BackpackBaseMenu.java:73) ~[travelersbackpack-neoforge-1.21.1-10.1.6.jar%23434!/:?]
5044 | at TRANSFORMER/travelersbackpack@10.1.6/com.tiviacz.travelersbackpack.inventory.menu.BackpackBaseMenu.<init>(BackpackBaseMenu.java:60) ~[travelersbackpack-neoforge-1.21.1-10.1.6.jar%23434!/:?]
5045 | at TRANSFORMER/travelersbackpack@10.1.6/com.tiviacz.travelersbackpack.inventory.menu.BackpackItemMenu.<init>(BackpackItemMenu.java:24) ~[travelersbackpack-neoforge-1.21.1-10.1.6.jar%23434!/:?]
5046 | at TRANSFORMER/travelersbackpack@10.1.6/com.tiviacz.travelersbackpack.inventory.menu.BackpackItemMenu.<init>(BackpackItemMenu.java:20) ~[travelersbackpack-neoforge-1.21.1-10.1.6.jar%23434!/:?]
5047 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.inventory.MenuType.create(MenuType.java:60) ~[client-1.21.1-20240808.144430-srg.jar%23309!/:?]
5048 | at TRANSFORMER/neoforge@21.1.83/net.neoforged.neoforge.network.handlers.ClientPayloadHandler.lambda$createMenuScreen$0(ClientPayloadHandler.java:127) ~[neoforge-21.1.83-universal.jar%23310!/:?]
5049 | at java.base/java.util.Optional.ifPresent(Unknown Source) ~[?:?]
5050 | at TRANSFORMER/neoforge@21.1.83/net.neoforged.neoforge.network.handlers.ClientPayloadHandler.createMenuScreen(ClientPayloadHandler.java:126) ~[neoforge-21.1.83-universal.jar%23310!/:?]
5051 | at TRANSFORMER/neoforge@21.1.83/net.neoforged.neoforge.network.handlers.ClientPayloadHandler.handle(ClientPayloadHandler.java:115) ~[neoforge-21.1.83-universal.jar%23310!/:?]
5052 | at TRANSFORMER/neoforge@21.1.83/net.neoforged.neoforge.network.handling.MainThreadPayloadHandler.lambda$handle$0(MainThreadPayloadHandler.java:16) ~[neoforge-21.1.83-universal.jar%23310!/:?]
5053 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:60) ~[client-1.21.1-20240808.144430-srg.jar%23309!/:?]
5054 | at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?]
5055 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:148) ~[client-1.21.1-20240808.144430-srg.jar%23309!/:?]
5056 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[client-1.21.1-20240808.144430-srg.jar%23309!/:?]
5057 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[client-1.21.1-20240808.144430-srg.jar%23309!/:?]
5058 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:111) ~[client-1.21.1-20240808.144430-srg.jar%23309!/:?]
5059 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1155) ~[client-1.21.1-20240808.144430-srg.jar%23309!/:?]
5060 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21.1-20240808.144430-srg.jar%23309!/:?]
5061 | at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23309!/:?]
5062 | at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
5063 | at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
5064 | at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.34.jar%23147!/:4.0]
5065 | at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.34.jar%23147!/:4.0]
5066 | at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.34.jar%23147!/:4.0]
5067 | at MC-BOOTSTRAP/fml_loader@4.0.34/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.34.jar%23147!/:4.0]
5068 | at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23153!/:?]
5069 | at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23153!/:?]
5070 | at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23153!/:?]
5071 | at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23153!/:?]
5072 | at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23153!/:?]
5073 | at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23153!/:?]
5074 | at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23153!/:?]
5075 | at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
5076 | at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]
5077 | [05Dec2024 16:19:50.272] [Render thread/INFO] [com.seibel.distanthorizons.core.api.internal.ClientApi/]: Client on ClientOnly mode disconnecting.
5078 | [05Dec2024 16:19:50.273] [Render thread/INFO] [DistantHorizons-com.seibel.distanthorizons.core.world.AbstractDhWorld/]: Unloading level [1364529072@minecraft:overworld].
5079 | [05Dec2024 16:19:50.273] [Render thread/INFO] [DistantHorizons-com.seibel.distanthorizons.core.level.ClientLevelModule$ClientRenderState/]: Shutting down ClientRenderState
5080 | [05Dec2024 16:19:50.273] [Render thread/INFO] [com.seibel.distanthorizons.core.render.renderer.LodRenderer/]: Shutting down LodRenderer...
5081 | [05Dec2024 16:19:50.273] [Render thread/INFO] [com.seibel.distanthorizons.core.render.renderer.LodRenderer/]: Queuing Renderer Cleanup for main render thread
5082 | [05Dec2024 16:19:50.292] [Render thread/INFO] [com.seibel.distanthorizons.core.render.renderer.LodRenderer/]: Finished shutting down LodRenderer
5083 | [05Dec2024 16:19:50.293] [Render thread/INFO] [DistantHorizons-com.seibel.distanthorizons.core.render.LodQuadTree/]: Shutting down LodQuadTree...
5084 | [05Dec2024 16:19:50.309] [Render thread/INFO] [DistantHorizons-com.seibel.distanthorizons.core.render.LodQuadTree/]: Finished shutting down LodQuadTree
5085 | [05Dec2024 16:19:50.510] [Render thread/INFO] [DistantHorizons-com.seibel.distanthorizons.core.file.AbstractDataSourceHandler/]: Closing [RemoteFullDataSourceProvider] for level: [DhClientLevel{1364529072@minecraft:overworld}].
5086 | [05Dec2024 16:19:50.510] [Render thread/INFO] [DistantHorizons-com.seibel.distanthorizons.core.file.fullDatafile.FullDataSourceProviderV1/]: Closing [FullDataSourceProviderV1] for level: [DhClientLevel{1364529072@minecraft:overworld}].
5087 | [05Dec2024 16:19:50.510] [Render thread/INFO] [DistantHorizons-com.seibel.distanthorizons.core.sql.repo.AbstractDhRepo/]: Closing database connection: [jdbc:sqlite:C:\Users\********\AppData\Roaming\ModrinthApp\profiles\New World 1.21.1\Distant_Horizons_server_data\REPLAY\1364529072@minecraft@@overworld\DistantHorizons.sqlite]
5088 | [05Dec2024 16:19:50.510] [DH-Parent Update Queue [1364529072@minecraft:overworld] Thread[0]/INFO] [DistantHorizons-com.seibel.distanthorizons.core.file.fullDatafile.FullDataSourceProviderV2/]: Update thread [DH-Parent Update Queue [1364529072@minecraft:overworld] Thread[0]] terminated.
5089 | [05Dec2024 16:19:50.523] [Render thread/INFO] [DistantHorizons-com.seibel.distanthorizons.core.level.DhClientLevel/]: Closed [DhClientLevel] for [Wrapped{ClientLevel@1364529072@minecraft:overworld}]
5090 | [05Dec2024 16:19:50.524] [Render thread/INFO] [DistantHorizons-com.seibel.distanthorizons.core.world.AbstractDhWorld/]: Closed DhWorld of type [CLIENT_ONLY].
5091 | [05Dec2024 16:19:50.524] [Render thread/INFO] [DistantHorizons-com.seibel.distanthorizons.core.sql.repo.AbstractDhRepo/]: Closing all [0] database connections...
5092 | [05Dec2024 16:19:50.941] [Render thread/INFO] [fr.rakambda.fallingtree.common.network.PacketUtils/]: Disconnected from server, resetting proxy config values
5093 | [05Dec2024 16:19:50.950] [Render thread/INFO] [DistantHorizons-com.seibel.distanthorizons.neoforge.NeoforgeClientProxy/]: level unload
5094 | [05Dec2024 16:19:50.950] [Render thread/INFO] [com.seibel.distanthorizons.core.api.internal.ClientApi/]: Unloading client level [ServerKeyedClientLevel]-[1364529072@minecraft:overworld].
5095 | [05Dec2024 16:19:50.953] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
5096 | [05Dec2024 16:19:51.058] [Render thread/WARN] [net.minecraft.client.multiplayer.ClientCommonPacketListenerImpl/]: Client disconnected with reason: Failed to open a screen with advanced data: java.lang.NullPointerException: Cannot invoke "com.tiviacz.travelersbackpack.inventory.BackpackWrapper.tanksVisible()" because "this.wrapper" is null

</body>
</html></details>

3. Write steps to reproduce the bug
Record a replay that goes from overworld to End, when attempting to do so, the game force closes the replay mod giving the above error.

4. What is expected behaviour 
To allow me to change dimensions within replaymod.

5. Screenshots (If applicable)
![image](https://github.com/user-attachments/assets/9b20aa21-a530-4647-aede-3b47c318513c)</details>

**Comment by Tiviacz1337** [comment]
Could you share the crash log? I tried to reproduce but it didnt crash for me
