### ISSUE TITLE
Crashes after adding tanks upgrade

### ISSUE THREAD

**Issue by dylanparry** [Tiviacz1337/Travelers-Backpack#1094]
Using the latest version of the mod (1.21.1-10.1.4) on Fabric and have just applied a water tank upgrade to my backpack (I think I applied it to the second slot as I'd put a crafting upgrade in the first slot, but as I released my mouse button I saw that the first slot was empty and the crafting table upgrade was in my inventory...). I got an instant crash out of the game and can no longer join my server without my game crashing instantly.

Here's a crash report from the client:

```
---- Minecraft Crash Report ----
// Oh - I know what I did wrong!

Time: 2024-12-16 15:18:12
Description: Unexpected error

java.util.NoSuchElementException: No value present
	at java.base/java.util.Optional.get(Optional.java:143)
	at knot//com.tiviacz.travelersbackpack.components.RenderInfo.getLeftFluidStack(RenderInfo.java:38)
	at knot//com.tiviacz.travelersbackpack.client.screens.HudOverlay.renderOverlay(HudOverlay.java:48)
	at knot//net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:28)
	at knot//net.minecraft.class_329.handler$bho000$fabric-rendering-v1$render(class_329.java:4538)
	at knot//net.minecraft.class_329.method_1753(class_329.java:220)
	at knot//net.minecraft.class_757.method_3192(class_757.java:896)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1285)
	at knot//net.minecraft.class_310.method_1514(class_310.java:882)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Optional.get(Optional.java:143)
	at knot//com.tiviacz.travelersbackpack.components.RenderInfo.getLeftFluidStack(RenderInfo.java:38)
	at knot//com.tiviacz.travelersbackpack.client.screens.HudOverlay.renderOverlay(HudOverlay.java:48)
	at knot//net.fabricmc.fabric.api.client.rendering.v1.HudRenderCallback.lambda$static$0(HudRenderCallback.java:28)
	at knot//net.minecraft.class_329.handler$bho000$fabric-rendering-v1$render(class_329.java:4538)
	at knot//net.minecraft.class_329.method_1753(class_329.java:220)

-- Uptime --
Details:
	JVM uptime: 24.876s
	Wall uptime: 18.530s
	High-res time: 15.390s
	Client ticks: 236 ticks / 11.800s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2501)
	at knot//net.minecraft.class_310.method_54580(class_310.java:949)
	at knot//net.minecraft.class_310.method_1514(class_310.java:905)
	at knot//net.minecraft.client.main.Main.main(Main.java:256)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Affected level --
Details:
	All players: 1 total; [class_746['deleted'/4165, l='ClientLevel', x=823.08, y=68.13, z=1488.81]]
	Chunk stats: 3025, 453
	Level dimension: minecraft:overworld
	Level spawn location: World: (32,67,-16), Section: (at 0,3,0 in 2,4,-1; chunk contains blocks 32,-64,-16 to 47,319,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 101701376 game time, 97045151 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
	Tracked entity count: 519

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: vanilla, fabric, ambientsounds, betteradvancements, betterclouds, betterf3, betterpingdisplay, blur, cardinal-components-base, cardinal-components-entity, cicada, clean_tooltips, clickthrough, cloth-config, cma, conditional-mixin, continuity, creativecore, distanthorizons, durabilitynotifier, dynamic_fps, easyanvils, enhancedblockentities, entity_model_features, entity_texture_features, entityculling, explosiveenhancement, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, forgeconfigapiport, held-item-info, horsebuff, immediatelyfast, items_displayed, jankson, libgui, midnightlib, modernfix, modmenu, moreculling, niftycarts, notenoughanimations, owo, particular, polymer-blocks, polymer-core, polymer-resource-pack, presencefootsteps, reeses-sodium-options, resourcepackoverrides, satin, showmeyourskin, shulkerboxtooltip, simpleupdatechecker, skinlayers3d, sodium, sodium-extra, sound_physics_remastered, travelersbackpack, visuality, voicechat, wakes, yet_another_config_lib_v3, yigd, server/00000000/705264ad-d01c-45ca-b184-0e0d250ed85a, file/§eTorches§0_§eReimagined§0_§8[v1.3.1]§0.zip, file/flowering-lily-pads_v1.zip, file/corality-1-0-3.zip, file/VanillaTweaks_r647984_MC1.21.x.zip, file/Simply 3D Extra's 1.20.0_1.0.0.zip, file/Simply 3D 1.20.0_1.0.0.zip, file/Simple Grass Flowers v1.6.0.zip, file/FreshAnimations_v1.9.zip, file/Fancy Crops v1.0 pf5-33.zip, file/Emissive_TXF_optifine_1.20.zip, file/CTM OF-Fabric 0.5.5+1.20.x.zip, file/Better+Lanterns+v1.1.3(mc-1.20.3-4).zip, file/1.20.x Better Glass Panes.zip, easyanvils:default_block_models, black_icons

-- System Details --
Details:
	Minecraft Version: 1.21.1
	Minecraft Version ID: 1.21.1
	Operating System: Linux (amd64) version 6.12.4-arch1-1
	Java Version: 21.0.5, Arch Linux
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Arch Linux
	Memory: 63973544 bytes (61 MiB) / 4311744512 bytes (4112 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 16
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
	Identifier: Intel64 Family 6 Model 141 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.30
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: TigerLake-H GT1 [UHD Graphics]
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MiB): 256.00
	Graphics card #0 deviceId: 0x9a60
	Graphics card #0 versionInfo: unknown
	Graphics card #1 name: GA106M [GeForce RTX 3060 Mobile / Max-Q]
	Graphics card #1 vendor: NVIDIA Corporation (0x10de)
	Graphics card #1 VRAM (MiB): 8224.00
	Graphics card #1 deviceId: 0x2520
	Graphics card #1 versionInfo: unknown
	Virtual memory max (MiB): 15936.28
	Virtual memory used (MiB): 11072.59
	Swap memory total (MiB): 0.00
	Swap memory used (MiB): 0.00
	Space in storage for jna.tmpdir (MiB): available: 362373.72, total: 937795.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 362373.72, total: 937795.00
	Space in storage for io.netty.native.workdir (MiB): available: 362373.72, total: 937795.00
	Space in storage for java.io.tmpdir (MiB): available: 15870.49, total: 15936.28
	Space in storage for workdir (MiB): available: 362373.72, total: 937795.00
	JVM Flags: 25 total; -Xmx12288M -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+AlwaysPreTouch -XX:+DisableExplicitGC -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=400M -XX:NonNMethodCodeHeapSize=12M -XX:ProfiledCodeHeapSize=194M -XX:NonProfiledCodeHeapSize=194M -XX:-DontCompileHugeMethods -XX:MaxNodeLimit=240000 -XX:NodeLimitFudgeFactor=8000 -XX:+UseVectorCmov -XX:+PerfDisableSharedMem -XX:+UseFastUnorderedTimeStamps -XX:+UseCriticalJavaThreadPriority -XX:ThreadPriorityPolicy=1 -XX:+UseShenandoahGC -XX:ShenandoahGCMode=iu -XX:ShenandoahGuaranteedGCInterval=1000000 -XX:AllocatePrefetchStyle=1 -XX:+UseTransparentHugePages -XX:ConcGCThreads=6
	Fabric Mods: 
		ambientsounds: AmbientSounds 6.1.4
		architectury: Architectury 13.0.8
		betteradvancements: Better Advancements 0.4.3.21
		betterclouds: Better Clouds 1.7.5+1.21-fabric
		betterf3: BetterF3 11.0.3
		betterpingdisplay: Better Ping Display 1.1.1
		blur: Blur+ (Fabric) 5.0.0
			midnightlib: MidnightLib 1.6.3
		cicada: CICADA 0.9.1+1.21-1.21.1
		clean_tooltips: Clean Tooltips 1.1
		clickthrough: ClickThrough Plus 3.0+1.21
		cloth-config: Cloth Config v15 15.0.140
			cloth-basic-math: cloth-basic-math 0.6.1
		cma: Coloured Map Arrows 1.0.3
		continuity: Continuity 3.0.0+1.21
		creativecore: CreativeCore 2.12.23
			net_neoforged_bus: bus 7.2.0
		distanthorizons: Distant Horizons 2.2.1-a
		durabilitynotifier: Durability Notifier 2.1.0
		dynamic_fps: Dynamic FPS 3.7.7
			net_lostluma_battery: battery 1.3.0
		easyanvils: Easy Anvils 21.1.0
		enhancedblockentities: Enhanced Block Entities 0.10.2+1.21
		entity_model_features: Entity Model Features 2.2.6
		entity_texture_features: Entity Texture Features 6.2.9
			org_apache_httpcomponents_httpmime: httpmime 4.5.10
		entityculling: EntityCulling 1.7.2
		explosiveenhancement: Explosive Enhancement 1.2.3-1.21.0
		fabric-api: Fabric API 0.110.0+1.21.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719
			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19
			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19
			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919
			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319
			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.0+da19b51a19
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.24+16c4ae2519
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919
			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519
			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519
			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19
			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319
			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19
			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.0+34f5d91419
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319
			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.88+b559734419
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19
			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+95bead5f19
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.2.0+45b9699719
		fabricloader: Fabric Loader 0.16.9
			mixinextras: MixinExtras 0.4.1
		ferritecore: FerriteCore 7.0.2-hotfix
		forgeconfigapiport: Forge Config API Port 21.1.3
			com_electronwill_night-config_core: core 3.8.0
			com_electronwill_night-config_toml: toml 3.8.0
		held-item-info: Held Item Info 1.7.0
		horsebuff: HorseBuff 2.1.8
		immediatelyfast: ImmediatelyFast 1.3.3+1.21.1
			net_lenni0451_reflect: Reflect 1.3.4
		items_displayed: Items Displayed 1.3
		java: OpenJDK 64-Bit Server VM 21
		maptooltip: Map Tooltip 4.0.1
		minecraft: Minecraft 1.21.1
		modernfix: ModernFix 5.19.6+mc1.21.1
		modmenu: Mod Menu 11.0.3
			fabric-api-base: Fabric API Base 0.4.42+6573ed8c90
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a790
			placeholder-api: Placeholder API 2.4.0-pre.2+1.21
		moreculling: More Culling 1.0.2
			conditional-mixin: conditional mixin 0.6.3
			mixinsquared: MixinSquared 0.2.0
		niftycarts: NiftyCarts 21.0.1
		notenoughanimations: NotEnoughAnimations 1.8.2
		owo: oωo 0.12.15+1.21
			io_wispforest_endec: endec 0.1.5
			io_wispforest_endec_gson: gson 0.1.3
			io_wispforest_endec_jankson: jankson 0.1.3
			io_wispforest_endec_netty: netty 0.1.2
		particular: Particular 1.1.1+1.21
		pickupnotifier: Pick Up Notifier 21.1.0
		polymer-bundled: Polymer 0.9.18+1.21.1
			polymer-blocks: Polymer (Textured Blocks) 0.9.18+1.21.1
			polymer-common: Polymer (Common) 0.9.18+1.21.1
				packet_tweaker: Packet Tweaker 0.5.5+1.21
			polymer-core: Polymer (Core) 0.9.18+1.21.1
				polymer-networking: Polymer (Networking) 0.9.18+1.21.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.9.18+1.21.1
			polymer-resource-pack: Polymer (Resource Pack) 0.9.18+1.21.1
			polymer-virtual-entity: Polymer (Virtual Entity) 0.9.18+1.21.1
		presencefootsteps: Presence Footsteps 1.10.3+1.21
			kirin: Kirin UI 1.20.0+1.21
		puzzleslib: Puzzles Lib 21.1.22
		reeses-sodium-options: Reese's Sodium Options 1.8.0+mc1.21.3
		resourcepackoverrides: Resource Pack Overrides 21.1.0
		showmeyourskin: Show Me Your Skin! 1.11.3+1.21
			cardinal-components-base: Cardinal Components API (base) 6.1.0
			cardinal-components-entity: Cardinal Components API (entities) 6.1.0
		shulkerboxtooltip: Shulker Box Tooltip 5.1.2+1.21.1
		simpleupdatechecker: Simple Update Checker 1.0.1+1.21.1
			server_translations_api: Server Translations API 2.3.1+1.21-pre2
		skinlayers3d: 3d-Skin-Layers 1.7.4
		sodium: Sodium 0.6.3+mc1.21.1
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19
		sodium-extra: Sodium Extra 0.6.0+mc1.21.1
		sound_physics_remastered: Sound Physics Remastered 1.21.1-1.4.8
		tia: Tiny Item Animations 1.2.1
		travelersbackpack: Traveler's Backpack 10.1.4
		visuality: Visuality 0.7.7+1.21
		voicechat: Simple Voice Chat 1.21.1-2.5.26
		wakes: Wakes 0.3.0+1.21.1
			com_github_jdiemke_delaunay-triangulator_delaunaytriangulator: DelaunayTriangulator 1.0.0
			satin: Satin 2.0.0
		yet_another_config_lib_v3: YetAnotherConfigLib 3.6.2+1.21-fabric
			com_twelvemonkeys_common_common-image: common-image 3.12.0
			com_twelvemonkeys_common_common-io: common-io 3.12.0
			com_twelvemonkeys_common_common-lang: common-lang 3.12.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.12.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.12.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.12.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yigd: You're in Grave Danger 2.4.11
			fabric-permissions-api-v0: fabric-permissions-api 0.3.1
			libgui: LibGui 11.0.0+1.21
				jankson: Jankson 8.0.0+j1.2.3
					blue_endless_jankson: jankson 1.2.3
				libninepatch: LibNinePatch 1.2.0
	Launched Version: 1.21.1
	Launcher name: theseus
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 565.77, NVIDIA Corporation
	Window size: 1920x1080
	GFLW Platform: x11
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 10/10 chunks
	Resource Packs: vanilla, fabric, ambientsounds, betteradvancements (incompatible), betterclouds, betterf3, betterpingdisplay, blur, cardinal-components-base, cardinal-components-entity, cicada, clean_tooltips, clickthrough, cloth-config, cma, conditional-mixin, continuity, creativecore, distanthorizons (incompatible), durabilitynotifier, dynamic_fps, easyanvils, enhancedblockentities, entity_model_features, entity_texture_features, entityculling, explosiveenhancement, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, forgeconfigapiport, held-item-info, horsebuff, immediatelyfast, items_displayed, jankson, libgui, midnightlib, modernfix (incompatible), modmenu, moreculling, niftycarts, notenoughanimations, owo, particular, polymer-blocks, polymer-core, polymer-resource-pack, presencefootsteps, reeses-sodium-options, resourcepackoverrides, satin, showmeyourskin, shulkerboxtooltip, simpleupdatechecker, skinlayers3d, sodium, sodium-extra, sound_physics_remastered, travelersbackpack, visuality, voicechat, wakes, yet_another_config_lib_v3 (incompatible), yigd, server/00000000/705264ad-d01c-45ca-b184-0e0d250ed85a, file/§eTorches§0_§eReimagined§0_§8[v1.3.1]§0.zip, file/flowering-lily-pads_v1.zip, file/corality-1-0-3.zip, file/VanillaTweaks_r647984_MC1.21.x.zip, file/Simply 3D Extra's 1.20.0_1.0.0.zip, file/Simply 3D 1.20.0_1.0.0.zip, file/Simple Grass Flowers v1.6.0.zip, file/FreshAnimations_v1.9.zip, file/Fancy Crops v1.0 pf5-33.zip, file/Emissive_TXF_optifine_1.20.zip, file/CTM OF-Fabric 0.5.5+1.20.x.zip, file/Better+Lanterns+v1.1.3(mc-1.20.3-4).zip, file/1.20.x Better Glass Panes.zip, easyanvils:default_block_models, black_icons
	Current Language: en_us
	Locale: en_GB
	System encoding: UTF-8
	File encoding: UTF-8
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
```

The server doesn't show anything other than the player joining and instantly leaving the server.

Any idea what's causing this? Is there a quick fix I can do to allow me to log back onto my server and play?

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/5997343
Fixed
