### ISSUE TITLE
Compat Issue after Update between YourInGraveDanger and Tracelersbackpack

### ISSUE THREAD

**Issue by suerion** [Tiviacz1337/Travelers-Backpack#1095]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric 1.21.1 on 0.16.9
Minecraft 1.21.1
You're in Grave Danger 2.4.11
[1.21.1] Traveler's Backpack 10.1.4

An a lot of more

1. Describe the bug 

Crash on Server Startup with YIGD
```
[22:16:41 ERROR] [main]: [Main] Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'yigd' at 'com.b1n_ry.yigd.Yigd'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.NoSuchFieldError: Class com.tiviacz.travelersbackpack.config.TravelersBackpackConfigData$BackpackSettings does not have member field 'boolean accessoriesIntegration'
        at knot/com.b1n_ry.yigd.compat.TravelersBackpackCompat.isAccessoriesIntegrationEnabled(TravelersBackpackCompat.java:22) ~[youre-in-grave-danger-fabric-2.4.11.jar:?]
        at knot/com.b1n_ry.yigd.compat.InvModCompat.reloadModCompat(InvModCompat.java:31) ~[youre-in-grave-danger-fabric-2.4.11.jar:?]
        at knot/com.b1n_ry.yigd.Yigd.onInitialize(Yigd.java:83) ~[youre-in-grave-danger-fabric-2.4.11.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more
```

2. Write steps to reproduce the bug

Add newest update 10.1.4

3. What is expected behaviour 

Server starts without issues.

4. Screenshots (If applicable)

**Comment by Tiviacz1337** [comment]
Need to report to yigd dev

**Comment by Tiviacz1337** [comment]
https://github.com/B1n-ry/Youre-in-grave-danger/issues/196
Fixed
