### ISSUE TITLE
Compat issue with REI plugin in your Mod

### ISSUE THREAD

**Issue by suerion** [Tiviacz1337/Travelers-Backpack#1102]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric 1.21.1 on 0.16.9
Windows Server 2019
RoughlyEnoughItems-16.0.788-fabric.jar
travelersbackpack-fabric-1.21.1-10.1.5

1. Describe the bug 

On Client side it Crash always the Game on Opening inventory
On Server Side it Crash on Server Starting

2. Write steps to reproduce the bug

Add REI and Travelers Backpak with actuall update in Modpack

3. What is expected behaviour 

Should not Crash Client or Server

4. Error

```
[17:58:35 ERROR] [main]: [Main] Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'roughlyenoughitems' at 'me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer::onInitialize'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
        at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.16.9-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.RuntimeException: Failed to initialize REI entry point: me.shedaniel.rei.RoughlyEnoughItemsCore
        at knot/me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:88) ~[RoughlyEnoughItems-16.0.788-fabric.jar:?]
        at knot/me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-16.0.788-fabric.jar:?]
        at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:199) ~[?:?]
        at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy71.onInitialize(Unknown Source) ~[?:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more
Caused by: java.lang.RuntimeException: Rerached side issue when loading REI plugin by Traveler's Backpack. Please use "rei_server", "rei_client" or "rei_common" instead.
        at knot/me.shedaniel.rei.RoughlyEnoughItemsState.error(RoughlyEnoughItemsState.java:52) ~[RoughlyEnoughItems-16.0.788-fabric.jar:?]
        at knot/me.shedaniel.rei.fabric.PluginDetectorImpl.loadPlugin(PluginDetectorImpl.java:108) ~[RoughlyEnoughItems-16.0.788-fabric.jar:?]
        at knot/me.shedaniel.rei.fabric.PluginDetectorImpl.detectCommonPlugins(PluginDetectorImpl.java:139) ~[RoughlyEnoughItems-16.0.788-fabric.jar:?]
        at knot/me.shedaniel.rei.RoughlyEnoughItemsCore.onInitialize(RoughlyEnoughItemsCore.java:155) ~[RoughlyEnoughItems-16.0.788-fabric.jar:?]
        at knot/me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:84) ~[RoughlyEnoughItems-16.0.788-fabric.jar:?]
        at knot/me.shedaniel.rei.impl.init.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-16.0.788-fabric.jar:?]
        at java.base/java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:199) ~[?:?]
        at jdk.proxy3/com.sun.proxy.jdk.proxy3.$Proxy71.onInitialize(Unknown Source) ~[?:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
        ... 7 more

```

**Comment by ardunster** [comment]
Same here, putting together a server modpack and as soon as I add Traveler's Backpack (with REI and already starting fine before that) it no longer starts. 

[latest.log](https://github.com/user-attachments/files/18234558/latest.log)


Someone filed a similar bug report on REI's GitHub for Twilight Forest, and the response was that it should be fixed by a Twilight Forest patch: https://github.com/shedaniel/RoughlyEnoughItems/issues/1173

**Comment by juxstified** [comment]
same here, I can disable REI on the server and leave it on client and the server will start no problem (but then we can't use the button to move items to the crafting grid for a recipe) so hoping to have this fixed!

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all?page=1&pageSize=20
Fixed

**Comment by ardunster** [comment]
Thanks, can confirm that my server starts fine with the new version!
