### ISSUE TITLE
Crash: "mouseReleased event handler"

### ISSUE THREAD

**Issue by Octofoxy** [Tiviacz1337/Travelers-Backpack#124]
Hello! I love your mod so far. However, it seems to crash the game randomly. I'm playing on a rented dedicated server with a friend. The error happens to both of us. The server runs fine, only our clients crash.

My backpack contains some lava and water, my friends backpack contains no liquids.

Crash Log:
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 6/27/20 8:38 PM
Description: mouseReleased event handler

java.lang.NullPointerException: mouseReleased event handler
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:88) ~[?:?] {re:classloading}
	at com.tiviacz.travelersbackpack.inventory.InventoryActions.transferContainerTank(InventoryActions.java:102) ~[?:1.15.2-4.0.4] {re:classloading}
	at com.tiviacz.travelersbackpack.inventory.TravelersBackpackInventory.updateTankSlots(TravelersBackpackInventory.java:133) ~[?:1.15.2-4.0.4] {re:classloading}
	at com.tiviacz.travelersbackpack.inventory.container.slot.FluidSlot.func_75218_e(FluidSlot.java:180) ~[?:1.15.2-4.0.4] {re:classloading}
	at com.tiviacz.travelersbackpack.inventory.container.slot.FluidSlot.func_75215_d(FluidSlot.java:171) ~[?:1.15.2-4.0.4] {re:classloading}
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:195) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.multiplayer.PlayerController.func_187098_a(PlayerController.java:374) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_184098_a(ContainerScreen.java:503) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.mouseReleased(ContainerScreen.java:463) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$1(MouseHelper.java:88) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$9243/420401784.run(Unknown Source) ~[?:?] {}
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:86) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$9223/1828826032.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.MouseHelper$$Lambda$7228/733346781.invoke(Unknown Source) ~[?:?] {}
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10] {}
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar:build 10] {}
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:105) ~[?:?] {re:classloading}
	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:375) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:946) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.27.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$426/101162229.call(Unknown Source) [forge-1.15.2-31.2.27.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:88)
	at com.tiviacz.travelersbackpack.inventory.InventoryActions.transferContainerTank(InventoryActions.java:102)
	at com.tiviacz.travelersbackpack.inventory.TravelersBackpackInventory.updateTankSlots(TravelersBackpackInventory.java:133)
	at com.tiviacz.travelersbackpack.inventory.container.slot.FluidSlot.func_75218_e(FluidSlot.java:180)
	at com.tiviacz.travelersbackpack.inventory.container.slot.FluidSlot.func_75215_d(FluidSlot.java:171)
	at net.minecraft.inventory.container.Container.func_184996_a(Container.java:195)
	at net.minecraft.client.multiplayer.PlayerController.func_187098_a(PlayerController.java:374)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_184098_a(ContainerScreen.java:503)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.mouseReleased(ContainerScreen.java:463)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$1(MouseHelper.java:88)
	at net.minecraft.client.MouseHelper$$Lambda$9243/420401784.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: com.tiviacz.travelersbackpack.client.gui.TravelersBackpackScreen
Stacktrace:
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:446)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:86)
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:163)
	at net.minecraft.client.MouseHelper$$Lambda$9223/1828826032.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:104)
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:162)
	at net.minecraft.client.MouseHelper$$Lambda$7228/733346781.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:105)

-- Affected level --
Details:
	All players: 2 total; [ClientPlayerEntity['Acrontas'/4685, l='MpServer', x=2098.20, y=115.00, z=519.26], RemoteClientPlayerEntity['FloMind'/12079, l='MpServer', x=2096.30, y=114.90, z=526.34]]
	Chunk stats: Client Chunk Cache: 2209, 1763
	Level dimension: DimensionType{minecraft:overworld}
	Level name: MpServer
	Level seed: 7199443325099092806
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-8,63,219), Chunk: (at 8,3,11 in -1,13; contains blocks -16,0,208 to -1,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 145123 game time, 149847 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$426/101162229.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5370169272 bytes (5121 MB) / 8457289728 bytes (8065 MB) up to 8457289728 bytes (8065 MB)
	CPUs: 8
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -Xms8G -XX:PermSize=256m
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.27.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.27.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.27.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.27.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre30.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.27.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.27
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.27-client.jar Minecraft {minecraft@1.15.2 DONE}
		torchmaster-2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 DONE}
		AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		Cucumber-1.15.2-3.0.8.jar Cucumber Library {cucumber@3.0.8 DONE}
		ImmersiveEngineering-0.15-103.jar Immersive Engineering {immersiveengineering@0.15-101 DONE}
		pamhc2trees-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		BiomesOPlenty-1.15.2-10.0.0.363-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.363 DONE}
		MekanismAdditions-1.15.2-9.10.8.421.jar Mekanism: Additions {mekanismadditions@9.10.8 DONE}
		pamhc2crops-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		refinedpipes-0.4.2.jar Refined Pipes {refinedpipes@0.4.2 DONE}
		jei-1.15.2-6.0.2.12.jar Just Enough Items {jei@6.0.2.12 DONE}
		DoggyTalents-1.15.2-1.15.2.3.jar Doggy Talents {doggytalents@1.15.2.3 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		Buzzier-Bees-1.15.2-1.5.1.jar Buzzier Bees {buzzierbees@1.5.1 DONE}
		usefultools-0.2.2.jar Useful Tools {usefultools@0.2.2 DONE}
		KiwiBirds-1.1.jar Kiwi Birds {kiwibirds@1.1 DONE}
		Mekanism-1.15.2-9.10.8.421.jar Mekanism {mekanism@9.10.8 DONE}
		MysticalAdaptations-1.15.2-1.1.jar Mystical Adaptations {mysticaladaptations@NONE DONE}
		jeiintegration_1.15.2-3.1.0.1.jar JEI Integration {jeiintegration@3.1.0.1 DONE}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 DONE}
		Botania-r1.15-386.jar Botania {botania@r1.15-386 DONE}
		Patchouli-1.15.2-1.2-34.jar Patchouli {patchouli@1.15.2-1.2-34 DONE}
		pamhc2foodcore-1.15.2-1.0.4.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		TravelersBackpack-1.15.2-4.0.4.jar Traveler's Backpack {travelersbackpack@4.0.4 DONE}
		StorageDrawers-1.15.2-7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 DONE}
		SimpleStorageNetwork-1.15.2-1.0.0.jar Simple Storage Network {storagenetwork@1.15.2-1.0.0 DONE}
		MysticalCustomization-1.15.2-1.0.0.jar Mystical Customization {mysticalcustomization@1.0.0 DONE}
		betteranimalsplus-1.15.2-8.2.1.96.jar Better Animals Plus {betteranimalsplus@8.2.1.96 DONE}
		structurize-0.10.324-ALPHA.jar Structurize {structurize@0.10.324-ALPHA DONE}
		mysticalkelpmod-1.2.2.jar Mystical Kelp Mod {mysticalkelpmod@1.15.2-1.2.2 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		minecolonies-1.15.2-0.11.961-universal.jar Minecolonies {minecolonies@1.15.2-0.11.961 DONE}
		MekanismTools-1.15.2-9.10.8.421.jar Mekanism: Tools {mekanismtools@9.10.8 DONE}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		AI-Improvements-1.15.2-0.3.0.jar AI-Improvements {aiimprovements@0.3.0 DONE}
		MekanismGenerators-1.15.2-9.10.8.421.jar Mekanism: Generators {mekanismgenerators@9.10.8 DONE}
		Netherite 1.15.2 - 0.1.6.jar Netherite 1.15.2 {netherite_dwny@1.0.0 DONE}
		beyond_the_nether_wastes_v_1.1.0.jar Beyond The Nether Wastes {btnw@1.0.0 DONE}
		forge-1.15.2-31.2.27-universal.jar Forge {forge@31.2.27 DONE}
		Aquaculture-1.15.2-2.0.15.jar Aquaculture 2 {aquaculture@1.15.2-2.0.15 DONE}
		mysticallib-1.15.2-2.0.0.jar Mystical Lib {mysticallib@1.15.2-2.0.0 DONE}
		MysticalCreations-1.15.2-1.0.jar Mystical Creations {mysticalcreations@NONE DONE}
		MysticalAgradditions-1.15.2-3.0.1.jar Mystical Agradditions {mysticalagradditions@3.0.1 DONE}
		refinedstorage-1.8.6.jar Refined Storage {refinedstorage@1.8.6 DONE}
		refinedstorageaddons-0.6.2.jar Refined Storage Addons {refinedstorageaddons@0.6.2 DONE}
		MysticalAgriculture-1.15.2-3.0.7.jar Mystical Agriculture {mysticalagriculture@3.0.7 DONE}
		Extended-Nether-1.15.2-beta 1.0.jar Extended Nether {extendednether@beta 1.0 DONE}
	Patchouli open book context: n/a
	Launched Version: forge-31.2.27
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 1500X Quad-Core Processor 
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre30
	OptiFine Build: 20200622-083032
	Render Distance Chunks: 20
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 446.14
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by Tiviacz1337** [comment]
Do you know any steps to reproduce this bug?

**Comment by Octofoxy** [comment]
1. Wear the backpack
2. Open backpack inventory
2. Drag an item (into the upper right corner of the backpack? Unsure.)

For the bug to occur, one must currently be dragging an item. It mostly seems to occur when moving the cursor with an item into the upper right corner of the backpack, but that might be coincidence. The game crashes when I move the mouse there, not when I pick an item up or place it. It's the cursor entering a certain area which seems to be causing the crash.

The bug only occurs every hour or so, sometimes it doesn't crash for 2-3 hours. It just now crashed again. This time while I was dragging an empty metal bucket into the upper right bucket slot to fill it with lava from the tank.

**Comment by Tiviacz1337** [comment]
Can't reproduce this, anyway next version should be available in a few days, so you'll can test if issue still occurs

**Comment by Octofoxy** [comment]
Alright... What will be different in the new version?

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/2995876 Check out this version, if bug still persists, comment here, so I'll open issue again.
