### ISSUE TITLE
Unexpectet errror

### ISSUE THREAD

**Issue by Schoolisoutfan** [Tiviacz1337/Travelers-Backpack#150]
Everytime I start a new 1.16.2 map the game crashes. 

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 27.08.20 09:58
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraftforge.common.util.LazyOptional.map(Lnet/minecraftforge/common/util/NonNullFunction;)Ljava/util/Optional;
	at com.tiviacz.travelersbackpack.capability.CapabilityUtils.isWearingBackpack(CapabilityUtils.java:34) ~[?:1.16.2-5.1.0] {re:classloading}
	at com.tiviacz.travelersbackpack.handlers.ClientEventHandler.clientTickEvent(ClientEventHandler.java:49) ~[?:1.16.2-5.1.0] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_26_ClientEventHandler_clientTickEvent_ClientTickEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?] {}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:110) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1511) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:931) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:585) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.2-33.0.19.jar:33.0] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$416/1240412896.call(Unknown Source) [forge-1.16.2-33.0.19.jar:33.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-6.1.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-6.1.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.tiviacz.travelersbackpack.capability.CapabilityUtils.isWearingBackpack(CapabilityUtils.java:34)
	at com.tiviacz.travelersbackpack.handlers.ClientEventHandler.clientTickEvent(ClientEventHandler.java:49)
	at net.minecraftforge.eventbus.ASMEventHandler_26_ClientEventHandler_clientTickEvent_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:110)

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['Schoolisoutfan'/24, l='ClientLevel', x=167.50, y=4.00, z=205.50]]
	Chunk stats: Client Chunk Cache: 4761, 443
	Level dimension: minecraft:overworld
	Level spawn location: World: (176,4,208), Chunk: (at 0,0,0 in 11,13; contains blocks 176,0,208 to 191,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 19 game time, 19 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1975)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:606)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$416/1240412896.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1755275984 bytes (1673 MB) / 2684354560 bytes (2560 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 6
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.2-33.0.19.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.19.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.2-33.0.19.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.19.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.2-33.0.19.jar fml TRANSFORMATIONSERVICE 
	FML: 33.0
	Forge: net.minecraftforge:33.0.19
	FML Language Providers: 
		javafml@33.0
		minecraft@1
	Mod List: 
		forge-1.16.2-33.0.19-client.jar Minecraft {minecraft@1.16.2 DONE}
		forge-1.16.2-33.0.19-universal.jar Forge {forge@33.0.19 DONE}
		TravelersBackpack-1.16.2-5.1.0.jar Traveler's Backpack {travelersbackpack@5.1.0 DONE}
	Launched Version: 1.16.2-forge-33.0.19
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/§lDefault§r..§l3D§r..High§0§o.zip (incompatible), file/ChromaHills-128x-1.15-v1.zip (incompatible), file/ChromaHills-128x-1.16-WALL-FIX.zip (incompatible), file/EPIC SOUNDS [addon for AmbientSounds mod].zip (incompatible)
	Current Language: Deutsch (Deutschland)
	CPU: 6x Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3050208
