### ISSUE TITLE
Server crash when equipping backpack

### ISSUE THREAD

**Issue by Jolo248** [Tiviacz1337/Travelers-Backpack#151]
Server is crashing when equipping the backpack.

Minecraft version : 1.16.2
Forge version : 33.0.21 
Mod version : TravelersBackpack-1.16.2-5.1.0.jar

`[27Aug2020 12:47:59.734] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoSuchMethodError: net.minecraftforge.common.util.LazyOptional.map(Lnet/minecraftforge/common/util/NonNullFunction;)Ljava/util/Optional;
	at com.tiviacz.travelersbackpack.capability.CapabilityUtils.isWearingBackpack(CapabilityUtils.java:34) ~[?:1.16.2-5.1.0]
	at com.tiviacz.travelersbackpack.network.EquipBackpackPacket.lambda$handle$0(EquipBackpackPacket.java:40) ~[?:1.16.2-5.1.0]
	at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[?:?]
	at com.tiviacz.travelersbackpack.network.EquipBackpackPacket.handle(EquipBackpackPacket.java:35) ~[?:1.16.2-5.1.0]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[?:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_252]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[?:?]
	at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[?:?]
	at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.3-service.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:73) ~[?:?]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_252]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:73) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1326) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:?]
	at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:729) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:156) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:712) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:706) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:691) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:229) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]`

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3050208

**Comment by Jolo248** [comment]
Hello! 

I just updated the mod to TravelersBackpack-1.16.2-5.1.1.jar on my client and on my server and I am still crashing when equipping the backpack (either from the ground or from inventory).

Here is my server crash log:
[crash-2020-09-09_10.22.09-server.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/5195833/crash-2020-09-09_10.22.09-server.txt)

Thanks!
