### ISSUE TITLE
Game Crash upon opening placed backpack

### ISSUE THREAD

**Issue by RNG-KingSlayer** [Tiviacz1337/Travelers-Backpack#229]
So the game crashed when I tried to open the backpack after i placed it on the ground.
Heres the crash report:
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2021/01/14 7:50 PM
Description: Unexpected error

java.lang.AbstractMethodError: Method com/tiviacz/travelersbackpack/tileentity/TravelersBackpackTileEntity.markDirty()V is abstract
	at com.tiviacz.travelersbackpack.tileentity.TravelersBackpackTileEntity.markDirty(TravelersBackpackTileEntity.java) ~[?:1.16.4-5.3.6] {re:classloading}
	at com.tiviacz.travelersbackpack.inventory.CraftingInventoryImproved.func_70296_d(CraftingInventoryImproved.java:84) ~[?:1.16.4-5.3.6] {re:classloading}
	at net.minecraft.inventory.container.Slot.func_75218_e(Slot.java:66) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.Slot.func_75215_d(Slot.java:62) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.Container.func_190896_a(Container.java:454) ~[?:?] {re:classloading}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147241_a(ClientPlayNetHandler.java:1112) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SWindowItemsPacket.func_148833_a(SourceFile:48) ~[?:?] {re:classloading}
	at net.minecraft.network.play.server.SWindowItemsPacket.func_148833_a(SourceFile:12) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.network.PacketThreadUtil$$Lambda$6644/1822695449.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:115) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:947) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.28.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$438/1925059423.call(Unknown Source) [forge-1.16.4-35.1.28.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.tiviacz.travelersbackpack.tileentity.TravelersBackpackTileEntity.markDirty(TravelersBackpackTileEntity.java) ~[?:1.16.4-5.3.6] {re:classloading}
	at com.tiviacz.travelersbackpack.inventory.CraftingInventoryImproved.func_70296_d(CraftingInventoryImproved.java:84) ~[?:1.16.4-5.3.6] {re:classloading}
	at net.minecraft.inventory.container.Slot.func_75218_e(Slot.java:66) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.Slot.func_75215_d(Slot.java:62) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.Container.func_190896_a(Container.java:454) ~[?:?] {re:classloading}
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147241_a(ClientPlayNetHandler.java:1112) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.network.play.server.SWindowItemsPacket.func_148833_a(SourceFile:48) ~[?:?] {re:classloading}
	at net.minecraft.network.play.server.SWindowItemsPacket.func_148833_a(SourceFile:12) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.network.PacketThreadUtil$$Lambda$6644/1822695449.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:172) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:134) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['YaBoiMemeDawg'/20646, l='ClientLevel', x=11648.24, y=79.00, z=3647.06]]
	Chunk stats: Client Chunk Cache: 441, 225
	Level dimension: minecraft:overworld
	Level spawn location: World: (3666,108,7931), Chunk: (at 2,6,11 in 229,495; contains blocks 3664,0,7920 to 3679,255,7935), Region: (7,15; contains chunks 224,480 to 255,511, blocks 3584,0,7680 to 4095,255,8191)
	Level time: 116813 game time, 192515 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:617) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2024) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:628) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.28.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$438/1925059423.call(Unknown Source) [forge-1.16.4-35.1.28.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 453713584 bytes (432 MB) / 2113929216 bytes (2016 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.28.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G5%20(1).jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.28.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.28
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.28-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.28-universal.jar                |Forge                         |forge                         |35.1.28             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		BiomesOPlenty-1.16.4-13.0.0.426-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.426   |DONE      |NOSIGNATURE
		ShoulderSurfing-1.16.4-2.0.2.jar                  |Shoulder Surfing              |shouldersurfing               |1.16.4-2.0.2        |DONE      |NOSIGNATURE
		MoreOresInONE-1.1.jar                             |More Ores in ONE              |moreoresinone                 |1.1                 |DONE      |NOSIGNATURE
		TerraForged-1.16.4-0.2.0-BETA-4.jar               |TerraForged                   |terraforged                   |0.2.0-BETA-4        |DONE      |7b:73:d0:a2:c3:40:13:84:35:4f:c9:0e:2b:85:8c:08:ea:3c:3c:eb:f1:98:8b:5b:6e:ca:8a:a0:9a:cf:12:b3
		FirstPersonMod-2.0.0-SNAPSHOT (1).jar             |FirstPersonModel Mod          |firstpersonmod                |2.0.0-SNAPSHOT      |DONE      |NOSIGNATURE
		SuperTools-1.1.jar                                |Super Tools                   |supertools                    |1.1                 |DONE      |NOSIGNATURE
		better_respawn-1.16.4-1.0.3.jar                   |Better Respawn                |better_respawn                |1.16.4-1.0.3        |DONE      |NOSIGNATURE
		TravelersBackpack-1.16.4-5.3.6.jar                |Traveler's Backpack           |travelersbackpack             |5.3.6               |DONE      |NOSIGNATURE
		jei-1.16.4-7.6.1.65.jar                           |Just Enough Items             |jei                           |7.6.1.65            |DONE      |NOSIGNATURE
	Crash Report UUID: 19ac5d01-2a92-4aed-897a-99d79052f0bf
	Launched Version: 1.16.4-forge-35.1.28
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1060 3GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 452.06, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, mod_resources
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 2600X Six-Core Processor 
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.2.zip
	OpenGlVersion: 4.6.0 NVIDIA 452.06
	OpenGlRenderer: GeForce GTX 1060 3GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

i just copy-pasted the crash report to here, i dont really know whether you need all of that information.
Anyway there you have it. Thanks!

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack/files/3166428

**Comment by RNG-KingSlayer** [comment]
thanks! also im an idiot.
i didnt even look for the other files. sorry :/
