### ISSUE TITLE
1.16.5 BedBenefits/Sleeping crashes game on sleeping bag

### ISSUE THREAD

**Issue by oliove** [Tiviacz1337/Travelers-Backpack#364]
Crash Report UUID:  1615dca4-73a5-4b3b-b35f-e74367718b93

When I open the sleep on the traveler's backpack sleeping bag I lay down and the screen fades, but as the screen goes black and the switch to day should happen the game crashes.  Here is the crash report info.  I will open an issue on the BedBenefits mod page as well. 

Time: 1/16/22 11:59 AM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/darkhax/bookshelf/util/EntityUtils
	at net.darkhax.bedbenefits.BedBenefits.onPlayerWakeUp(BedBenefits.java:47) ~[?:5.0.3] {re:classloading}
	at net.darkhax.bedbenefits.BedBenefits$$Lambda$3370/488576416.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3016/1225926739.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$3222/1716832781.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event
[crash-2022-01-16_11.59.40-server.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/7877604/crash-2022-01-16_11.59.40-server.txt)
bus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPlayerWakeup(ForgeEventFactory.java:481) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.PlayerEntity.func_225652_a_(PlayerEntity.java:1259) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:computing_frames,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:classloading,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.ServerPlayerEntity.func_225652_a_(ServerPlayerEntity.java:820) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:ServerPlayerEntityMixin,pl:mixin:A}
	at net.minecraft.entity.player.PlayerEntity.func_213366_dy(PlayerEntity.java:1269) ~[?:?] {re:mixin,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:computing_frames,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,re:classloading,pl:accesstransformer:B,xf:fml:tlskincape:PlayerEntityTransformer,pl:mixin:APP:betterendforge.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at vazkii.quark.content.tweaks.module.ImprovedSleepingModule$$Lambda$13614/270612983.accept(Unknown Source) ~

**Comment by Tiviacz1337** [comment]
Well, that's not caused by traveler's backpack I think
