### ISSUE TITLE
Failing Twilight Forest's Uncrafting Table

### ISSUE THREAD

**Issue by Neubulae** [Tiviacz1337/Travelers-Backpack#465]
**Describe the bug**
Using the Uncrafting Table to uncraft items doesn't lead to results, instead it consumes XP and does nothing.

**Log**
```
[04:35:54] [Server thread/ERROR] (class_1255) Error executing task on Server
 java.lang.AbstractMethodError: Method com/tiviacz/travelersbackpack/common/BackpackDyeRecipe.method_8113(II)Z is abstract
        at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.14) ~[?:?]
        at com.tiviacz.travelersbackpack.common.BackpackDyeRecipe.fits(BackpackDyeRecipe.java) ~[travelers-backpack-1.18.2-7.1.5.jar:?]
        at twilightforest.inventory.UncraftingContainer.getRecipesFor(UncraftingContainer.java:303) ~[twilightforest-fabric-1.18.2-4.1.268.jar:?]
        at twilightforest.inventory.UncraftingContainer.onContentChanged(UncraftingContainer.java:113) ~[twilightforest-fabric-1.18.2-4.1.268.jar:?]
        at twilightforest.inventory.UncraftingInputInventory.setStack(UncraftingInputInventory.java:66) ~[twilightforest-fabric-1.18.2-4.1.268.jar:?]
        at net.minecraft.screen.slot.Slot.setStack(Slot:61) ~[?:?]
        at net.minecraft.screen.slot.Slot.insertStack(Slot:146) ~[?:?]
        at net.minecraft.screen.ScreenHandler.internalOnSlotClick(ScreenHandler:416) ~[?:?]
        at net.minecraft.screen.ScreenHandler.onSlotClick(ScreenHandler:295) ~[?:?]
        at twilightforest.inventory.UncraftingContainer.onSlotClick(UncraftingContainer.java:499) ~[twilightforest-fabric-1.18.2-4.1.268.jar:?]
        at net.minecraft.server.network.ServerPlayNetworkHandler.onClickSlot(ServerPlayNetworkHandler:1436) ~[?:?]
        at net.minecraft.network.packet.c2s.play.ClickSlotC2SPacket.apply(ClickSlotC2SPacket:58) ~[?:?]
        at net.minecraft.network.packet.c2s.play.ClickSlotC2SPacket.apply(ClickSlotC2SPacket:13) ~[?:?]
        at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:22) ~[?:?]
        at net.minecraft.server.ServerTask.run(ServerTask:18) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.redirect$bka000$redirectExecuteTask(ThreadExecutor:521) ~[?:?]
        at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
        at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:16788) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:784) ~[server-intermediary.jar:?]
        at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
        at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:768) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$bpj000$modifiedRunLoop(MinecraftServer:5405) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:676) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]

```

**Required informations (please complete the following information):**
 - Mod version: 1.18.2-7.1.5
- Mod Loader: Fabric

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/3946813

**Comment by Neubulae** [comment]
thx
