### ISSUE TITLE
compatibility issues with fabric

### ISSUE THREAD

**Issue by kimayu05** [Tiviacz1337/Travelers-Backpack#474]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install cardinal-components-base, any version.
	 - Install cardinal-components-entity, any version.
Unmet dependency listing:
	 - Mod 'Traveler's Backpack' (travelersbackpack) 1.19.2-8.2.0 requires any version of cardinal-components-base, which is missing!
	 - Mod 'Traveler's Backpack' (travelersbackpack) 1.19.2-8.2.0 requires any version of cardinal-components-entity, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at net.digitalingot.rustextension.ProxiedStart.main(ProxiedStart.java:16)

Minecraft 1.19.2 won't run.
(It may be strange because I wrote it in English with a translator)

**Comment by kimayu05** [comment]
그냥 안됨

**Comment by Tiviacz1337** [comment]
- Install cardinal-components-base, any version.
- Install cardinal-components-entity, any version.
please use eyes and read what it says, just download cardinal components...
