### ISSUE TITLE
Warning displayed on launch - version check failed

### ISSUE THREAD

**Issue by shaneknysh** [Tiviacz1337/Travelers-Backpack#490]
**Describe the bug**
During server launch a warning is logged. No in game issue is observed (so far). 

```
[21:39:35] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [travelersbackpack] Starting version check at https://gist.githubusercontent.com/Tiviacz1337/906937677aa472285dff9d6c2a189d5e/raw
[21:39:35] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Expected name at line 143 column 3 path $..6.0.17
        at com.google.gson.Gson.fromJson(Gson.java:978) ~[gson-2.8.9.jar%2370!/:?] {re:mixin}
        at com.google.gson.Gson.fromJson(Gson.java:928) ~[gson-2.8.9.jar%2370!/:?] {re:mixin}
        at com.google.gson.Gson.fromJson(Gson.java:877) ~[gson-2.8.9.jar%2370!/:?] {re:mixin}
        at com.google.gson.Gson.fromJson(Gson.java:848) ~[gson-2.8.9.jar%2370!/:?] {re:mixin}
        at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:183) ~[fmlcore-1.19.2-43.1.16.jar%23126!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) [?:?] {re:mixin}
```
**To Reproduce**

1. Launch server
2. View startup logging

**Expected behavior**
no warning is logged

**Screenshots**
n/a

**Required informations (please complete the following information):**
- Mod version: both 8.2.0 and 8.2.2
- Mod Loader: Forge 43.1.16

**Additional context**
n/a

**Comment by Tiviacz1337** [comment]
Thank you, fixed
