### ISSUE TITLE
Dragon Backpack - Ticking Entity

### ISSUE THREAD

**Issue by Nydid** [Tiviacz1337/Travelers-Backpack#513]
**Describe the bug**
While wearing the dragon backpack on your back, you enter water. Whenever water reaches head level, the game crashes

**To Reproduce**
1. Wear Dragon backpack
2. Go underwater
3. Crash

**Expected behavior**
1. Wear Dragon backpack
2. Go underwater
3. Get buffs

**Required informations (please complete the following information):**
 - Mod version: travelers-backpack-1.18.2-7.1.12
- Mod Loader: Fabric Loader
- AMD GPU

**Additional context**
---- Minecraft Crash Report ----
// Don't do that.

Time: 11/24/22, 9:31 PM
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1293.method_5584()" because the return value of "net.minecraft.class_1657.method_6112(net.minecraft.class_1291)" is null
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.addTimedStatusEffect(BackpackAbilities.java:640)
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.batAbility(BackpackAbilities.java:557)
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.squidAbility(BackpackAbilities.java:612)
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.dragonAbility(BackpackAbilities.java:474)
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.abilityTick(BackpackAbilities.java:106)
	at com.tiviacz.travelersbackpack.inventory.TravelersBackpackInventory.abilityTick(TravelersBackpackInventory.java:330)
	at net.minecraft.class_1657.handler$fgm000$abilityTick(class_1657.java:26858)
	at net.minecraft.class_1657.method_5773(class_1657.java:324)
	at net.minecraft.class_746.method_5773(class_746.java:212)
	at net.minecraft.class_638.method_18646(class_638.java:217)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_638.method_32124(class_638.java:200)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:196)
	at net.minecraft.class_310.method_1574(class_310.java:1761)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.addTimedStatusEffect(BackpackAbilities.java:640)
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.batAbility(BackpackAbilities.java:557)
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.squidAbility(BackpackAbilities.java:612)
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.dragonAbility(BackpackAbilities.java:474)
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.abilityTick(BackpackAbilities.java:106)
	at com.tiviacz.travelersbackpack.inventory.TravelersBackpackInventory.abilityTick(TravelersBackpackInventory.java:330)
	at net.minecraft.class_1657.handler$fgm000$abilityTick(class_1657.java:26858)
	at net.minecraft.class_1657.method_5773(class_1657.java:324)
	at net.minecraft.class_746.method_5773(class_746.java:212)
	at net.minecraft.class_638.method_18646(class_638.java:217)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_638.method_32124(class_638.java:200)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:196)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_746)
	Entity ID: 81618
	Entity Name: Nydid
	Entity's Exact location: 365.27, 60.03, 116.71
	Entity's Block location: World: (365,60,116), Section: (at 13,12,4 in 22,3,7; chunk contains blocks 352,-64,112 to 367,319,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Entity's Momentum: 0.89, -1.03, -0.07
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_638.method_32124(class_638.java:200)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_638.method_18116(class_638.java:196)
	at net.minecraft.class_310.method_1574(class_310.java:1761)
	at net.minecraft.class_310.method_1523(class_310.java:1091)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
Details:
	Chunk stats: 1024, 755
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,63,0), Section: (at 0,15,0 in 0,3,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 13565770 game time, 6516567 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:407)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:756)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by Tiviacz1337** [comment]
May I know your fabric version

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files/all fixed
