### ISSUE TITLE
Crash Description: Rendering entity in world

### ISSUE THREAD

**Issue by alejandrogiraldoq** [Tiviacz1337/Travelers-Backpack#564]
Fabric 1.19.3
I was in creative mode, I took out a backpack and when I look at the game inventory it crashes

Description: Rendering entity in world

java.lang.NoClassDefFoundError: dev/emi/trinkets/api/Trinket
	at com.tiviacz.travelersbackpack.client.renderer.TravelersBackpackFeature.render(TravelersBackpackFeature.java:51)
	at com.tiviacz.travelersbackpack.client.renderer.TravelersBackpackFeature.method_4199(TravelersBackpackFeature.java:29)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_1007.method_4215(class_1007.java:63)
	at net.minecraft.class_1007.method_3936(class_1007.java:41)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_490.method_29977(class_490.java:152)
	at com.mojang.blaze3d.systems.RenderSystem.runAsFancy(RenderSystem.java:1164)
	at net.minecraft.class_490.method_2486(class_490.java:152)
	at net.minecraft.class_481.method_2389(class_481.java:814)
	at net.minecraft.class_465.method_25394(class_465.java:99)
	at net.minecraft.class_485.method_25394(class_485.java:27)
	at net.minecraft.class_481.method_25394(class_481.java:732)
	at net.minecraft.class_437.method_47413(class_437.java:113)
	at net.minecraft.class_757.method_3192(class_757.java:929)
	at net.minecraft.class_310.method_1523(class_310.java:1193)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: dev.emi.trinkets.api.Trinket
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 22 more

**Comment by Tiviacz1337** [comment]
Do you have trinkets installed?

**Comment by alejandrogiraldoq** [comment]
here is my server mod list:

1. trinkets-3.5.1

2. travelers-backpack-1.19.3-8.3.3

3. fabric-api-0.75.1+1.19.3

4. cloth-config-9.0.94-fabric

5. cardinal-components-api-5.1.0

6. essential_commands-0.31.1-mc1.19.3.jar

7.jei-1.19.3-fabric-12.3.0.18.jar
