### ISSUE TITLE
Shift clicking an item into a memory slot from inventory crashes the game

### ISSUE THREAD

**Issue by Frontear** [Tiviacz1337/Travelers-Backpack#585]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 1.19.2-8.2.18

1. Describe the bug 
Shift clicking an item from your inventory into the backpack interface, assuming there is one object already present occupying a memory slot, will cause the game to crash.
It should be noted the item is from a mod and is entirely possible that this item is incorrectly coded. However, this always worked in older versions of travellers backpack, and I did notice there was a changelog about memory slots, so I decided to submit this.

2. Write steps to reproduce the bug
As above

3. What is expected behaviour 
That it wont crash and will move the item as intended to the correct slot

4. Relevant log entries:

Full log: https://mclo.gs/NyrN83u

```log
[18:16:54] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.util.crash.CrashException: Container click
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:494) ~[client-intermediary.jar:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.client.Mouse.method_22686(Mouse.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor.java:103) ~[client-intermediary.jar:?]
	at net.minecraft.client.Mouse.method_22684(Mouse.java:165) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:197) ~[client-intermediary.jar:?]
	at net.minecraft.client.util.Window.swapBuffers(Window.java:315) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1205) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.19.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.nbt.NbtCompound.contains(String)" because "copy1" is null
	at com.tiviacz.travelersbackpack.util.ItemStackUtils.areTagsEqual(ItemStackUtils.java:25) ~[travelers-backpack-1.19.2-8.2.18.jar:?]
	at com.tiviacz.travelersbackpack.util.ItemStackUtils.canCombine(ItemStackUtils.java:10) ~[travelers-backpack-1.19.2-8.2.18.jar:?]
	at com.tiviacz.travelersbackpack.inventory.screen.TravelersBackpackBaseScreenHandler.transferSlot(TravelersBackpackBaseScreenHandler.java:254) ~[travelers-backpack-1.19.2-8.2.18.jar:?]
	at net.minecraft.screen.ScreenHandler.internalOnSlotClick(ScreenHandler.java:394) ~[client-intermediary.jar:?]
	at net.minecraft.screen.ScreenHandler.onSlotClick(ScreenHandler.java:293) ~[client-intermediary.jar:?]
	at com.tiviacz.travelersbackpack.inventory.screen.TravelersBackpackBaseScreenHandler.onSlotClick(TravelersBackpackBaseScreenHandler.java:415) ~[travelers-backpack-1.19.2-8.2.18.jar:?]
	at com.tiviacz.travelersbackpack.inventory.screen.TravelersBackpackItemScreenHandler.onSlotClick(TravelersBackpackItemScreenHandler.java:89) ~[travelers-backpack-1.19.2-8.2.18.jar:?]
	at net.minecraft.client.network.ClientPlayerInteractionManager.clickSlot(ClientPlayerInteractionManager.java:450) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.ingame.HandledScreen.onMouseClick(HandledScreen.java:569) ~[client-intermediary.jar:?]
	at com.tiviacz.travelersbackpack.client.screen.TravelersBackpackHandledScreen.onMouseClick(TravelersBackpackHandledScreen.java:410) ~[travelers-backpack-1.19.2-8.2.18.jar:?]
	at net.minecraft.client.gui.screen.ingame.HandledScreen.mouseClicked(HandledScreen.java:361) ~[client-intermediary.jar:?]
	at com.tiviacz.travelersbackpack.client.screen.TravelersBackpackHandledScreen.mouseClicked(TravelersBackpackHandledScreen.java:518) ~[travelers-backpack-1.19.2-8.2.18.jar:?]
	at net.minecraft.client.Mouse.method_1611(Mouse.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen.java:489) ~[client-intermediary.jar:?]
	... 19 more
```

**Comment by jeytee84** [comment]
Happened to me too, crash log hoping it helps: https://mclo.gs/EtzLpsC Might be related to the feature request i asked for so now i feel bad :D :D https://github.com/Tiviacz1337/Travelers-Backpack/issues/579

**Comment by Tiviacz1337** [comment]
Fixed
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
https://modrinth.com/mod/travelersbackpack/versions
