### ISSUE TITLE
If the backpack is worn at death, a crash occurs

### ISSUE THREAD

**Issue by ReactorNefg** [Tiviacz1337/Travelers-Backpack#586]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

0.travelers-backpack-1.16.5-5.4.25

1. Describe the bug 

If the backpack is worn at death, a crash occurs

2. Write steps to reproduce the bug

java.lang.NoSuchMethodError: net.minecraft.class_2507.method_10630(Lnet/minecraft/class_2487;Ljava/io/File;)V
	at com.tiviacz.travelersbackpack.common.BackpackManager.addBackpack(BackpackManager.java:26) ~[travelers-backpack-1.16.5-5.4.25.jar:?]
	at com.tiviacz.travelersbackpack.util.BackpackUtils.onPlayerDeath(BackpackUtils.java:27) ~[travelers-backpack-1.16.5-5.4.25.jar:?]
	at net.minecraft.class_1309.handler$bki000$travelersbackpack$onDeath(class_1309.java:9345) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_16078(class_1309.java) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_16078(class_1657.java:665) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_16080(class_1309.java:1296) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_6078(class_3222.java:540) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5643(class_1309.java:1106) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5643(class_1657.java:914) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_5643(class_3222.java:631) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5747(class_1309.java:1453) ~[server-intermediary.jar:?]
	at net.minecraft.class_1657.method_5747(class_1657.java:1676) ~[server-intermediary.jar:?]
	at net.minecraft.class_2248.method_9554(class_2248.java:424) ~[server-intermediary.jar:?]
	at net.minecraft.class_1297.method_5623(class_1297.java:1049) ~[server-intermediary.jar:?]
	at net.minecraft.class_1309.method_5623(class_1309.java:300) ~[server-intermediary.jar:?]
	at net.minecraft.class_3222.method_14207(class_3222.java:926) ~[server-intermediary.jar:?]
	at net.minecraft.class_3244.method_12063(class_3244.java:932) ~[server-intermediary.jar:?]
	at net.minecraft.class_2828.method_12272(class_2828.java:122) ~[server-intermediary.jar:?]
	at net.minecraft.class_2828$class_2830.method_11054(class_2828.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:127) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:722) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zif000$carpet$modifiedRunLoop(MinecraftServer.java:5319) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]

**Comment by ReactorNefg** [comment]
> give me whole crash log

https://pastebin.com/g9cCFvDK

**Comment by Tiviacz1337** [comment]
Fixed
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files
https://modrinth.com/mod/travelersbackpack/versions
