### ISSUE TITLE
Game crashes, compat issues with Jei 1.19.4

### ISSUE THREAD

**Issue by Ruecookie** [Tiviacz1337/Travelers-Backpack#590]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
forge
also I would provide a crash report, I don't know which part to send tho (Im not a very tech person, sorry)

2. Describe the bug 
I went in a world, even a new world, and press e, and it crashes

3. Write steps to reproduce the bug
just open inventory

4. What is expected behaviour 
to open inventory
Just figured out it has compat issues with Jei

5. Screenshots (If applicable)

**Comment by Ruecookie** [comment]
`---- Minecraft Crash Report ----
// My bad.

Time: 2023-04-17 10:38:38
Description: Unexpected error

java.lang.IllegalArgumentException: width must be >= 0
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar%2399!/:?] {}
	at mezz.jei.common.util.ImmutableRect2i.<init>(ImmutableRect2i.java:24) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.common.util.ImmutableRect2i.insetBy(ImmutableRect2i.java:101) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.updateGridBounds(IngredientGridWithNavigation.java:150) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.updateBounds(IngredientGridWithNavigation.java:195) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.gui.overlay.bookmarks.BookmarkOverlay.updateBounds(BookmarkOverlay.java:109) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.gui.overlay.bookmarks.BookmarkOverlay.lambda$onScreenPropertiesChanged$1(BookmarkOverlay.java:101) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at java.util.Optional.ifPresentOrElse(Optional.java:196) ~[?:?] {re:mixin}
	at mezz.jei.gui.overlay.bookmarks.BookmarkOverlay.onScreenPropertiesChanged(BookmarkOverlay.java:99) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.gui.overlay.ScreenPropertiesCache.updateScreen(ScreenPropertiesCache.java:39) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.gui.overlay.bookmarks.BookmarkOverlay.updateScreen(BookmarkOverlay.java:94) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.gui.events.GuiEventHandler.onGuiInit(GuiEventHandler.java:56) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.forge.startup.EventRegistration.lambda$registerGuiHandler$10(EventRegistration.java:90) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.core.util.WeakConsumer.accept(WeakConsumer.java:17) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraft.client.gui.screens.Screen.m_6575_(Screen.java:478) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91152_(Minecraft.java:1021) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1944) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1807) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1126) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:731) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[1.19.4-forge-45.0.43.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.4-45.0.43.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar%2399!/:?] {}
	at mezz.jei.common.util.ImmutableRect2i.<init>(ImmutableRect2i.java:24) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.common.util.ImmutableRect2i.insetBy(ImmutableRect2i.java:101) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.updateGridBounds(IngredientGridWithNavigation.java:150) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.gui.overlay.IngredientGridWithNavigation.updateBounds(IngredientGridWithNavigation.java:195) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.gui.overlay.bookmarks.BookmarkOverlay.updateBounds(BookmarkOverlay.java:109) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.gui.overlay.bookmarks.BookmarkOverlay.lambda$onScreenPropertiesChanged$1(BookmarkOverlay.java:101) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at java.util.Optional.ifPresentOrElse(Optional.java:196) ~[?:?] {re:mixin}
	at mezz.jei.gui.overlay.bookmarks.BookmarkOverlay.onScreenPropertiesChanged(BookmarkOverlay.java:99) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.gui.overlay.ScreenPropertiesCache.updateScreen(ScreenPropertiesCache.java:39) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.gui.overlay.bookmarks.BookmarkOverlay.updateScreen(BookmarkOverlay.java:94) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.gui.events.GuiEventHandler.onGuiInit(GuiEventHandler.java:56) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.forge.startup.EventRegistration.lambda$registerGuiHandler$10(EventRegistration.java:90) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at mezz.jei.core.util.WeakConsumer.accept(WeakConsumer.java:17) ~[jei-1.19.4-forge-13.1.0.5.jar%23161!/:13.1.0.5] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraft.client.gui.screens.Screen.m_6575_(Screen.java:478) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91152_(Minecraft.java:1021) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1944) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
-- Affected level --
Details:
	All players: 1 total; [LocalPlayer['RuelleFoox'/240, l='ClientLevel', x=7.50, y=110.00, z=-38.50]]
	Chunk stats: 529, 322
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,109,-48), Section: (at 0,13,0 in 1,6,-3; chunk contains blocks 16,-64,-48 to 31,319,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 135 game time, 135 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.ClientLevel.m_6026_(ClientLevel.java:583) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2334) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:753) ~[client-1.19.4-20230314.122934-srg.jar%23164!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bookshelf.common.mixins.json:accessors.client.AccessorMinecraft,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[1.19.4-forge-45.0.43.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.4-45.0.43.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: mod_resources, vanilla, file/EarthFoxes.zip, file/fhaeriesFloralTools-Resource-Pack-16x-1.19.zip, file/aadjusted-fences-walls.zip, file/froggy-hotbar.zip, file/pink-jungle-wood-e2000.zip, file/Amethyest Armor, file/From-The-Fog-1.19-v1.8.1-Data-Resource-Pack.zip

-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 996337960 bytes (950 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x1638
	Graphics card #0 versionInfo: DriverVersion=30.0.13002.19003
	Graphics card #1 name: NVIDIA GeForce RTX 3050 Ti Laptop GPU
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x25a0
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3141
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18206.80
	Virtual memory used (MB): 15336.80
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 67.91
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.19.4-forge-45.0.43
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.14761 Core Profile Forward-Compatible Context 21.30.02.19 30.0.13002.19003, ATI Technologies Inc.
	Window size: 1920x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: mod_resources, vanilla, file/EarthFoxes.zip (incompatible), file/fhaeriesFloralTools-Resource-Pack-16x-1.19.zip (incompatible), file/aadjusted-fences-walls.zip (incompatible), file/froggy-hotbar.zip (incompatible), file/pink-jungle-wood-e2000.zip (incompatible), file/Amethyest Armor (incompatible), file/From-The-Fog-1.19-v1.8.1-Data-Resource-Pack.zip (incompatible)
	Current Language: en_us
	CPU: 16x AMD Ryzen 7 5800H with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['RuelleFoox'/240, l='ServerLevel[New World]', x=7.50, y=110.00, z=-38.50]]
	Data Packs: vanilla, mod:bookshelf (incompatible), mod:forge, mod:respawningpets (incompatible), mod:curios (incompatible), mod:clumps (incompatible), mod:journeymap (incompatible), mod:watching, mod:travelersbackpack (incompatible), mod:jei (incompatible)
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Experimental
	OptiFine Version: OptiFine_1.19.4_HD_U_I4
	OptiFine Build: 20230408-043701
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.14761 Core Profile Forward-Compatible Context 21.30.02.19 30.0.13002.19003
	OpenGlRenderer: AMD Radeon(TM) Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 16
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.4-45.0.43.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.4-45.0.43.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.4-45.0.43.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.4-45.0.43.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.4-45.0.43.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.4-20230314.122934-srg.jar             |Minecraft                     |minecraft                     |1.19.4              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		Bookshelf-Forge-1.19.4-18.0.2.jar                 |Bookshelf                     |bookshelf                     |18.0.2              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		forge-1.19.4-45.0.43-universal.jar                |Forge                         |forge                         |45.0.43             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Eternal-Pets-1.19-v1.1.3-Forge.jar                |Eternal Pets                  |respawningpets                |1.1.3               |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.19.4-5.1.5.0.jar                   |Curios API                    |curios                        |1.19.4-5.1.5.0      |DONE      |Manifest: NOSIGNATURE
		Clumps-forge-1.19.4-10.0.0.2.jar                  |Clumps                        |clumps                        |10.0.0.2            |DONE      |Manifest: NOSIGNATURE
		journeymap-1.19.4-5.9.5-forge.jar                 |Journeymap                    |journeymap                    |5.9.5               |DONE      |Manifest: NOSIGNATURE
		From-The-Fog-1.19-v1.8.1-Forge-Fabric.jar         |From The Fog                  |watching                      |1.8.1               |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.19.4-8.4.1.jar                |Traveler's Backpack           |travelersbackpack             |8.4.1               |DONE      |Manifest: NOSIGNATURE
		jei-1.19.4-forge-13.1.0.5.jar                     |Just Enough Items             |jei                           |13.1.0.5            |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 33ddcc63-16d2-4647-a0ef-0c5d344006c1
	FML: 45.0
	Forge: net.minecraftforge:45.0.43`

**Comment by Tiviacz1337** [comment]
Are you sure this issue is Traveler's backpack fault?

**Comment by Tiviacz1337** [comment]
Just tested with Traveler's Backpack 1.19.4-8.4.1 and latest JEI and issue does not occur
