### ISSUE TITLE
Mod crashes the game when brute piglins are spawned

### ISSUE THREAD

**Issue by Object417** [Tiviacz1337/Travelers-Backpack#600]
## Info

Minecraft 1.16.5
Fabric 0.14.19
Mod versions: 5.4.26, 5.4.25

## Bug description

The game crashes when trying to render brute piglin. Exit code:

```
java.util.NoSuchElementException: class_5419['Piglin Brute'/271, l='ClientLevel', x=137.56, y=58.00, z=246.16] provides no component of type travelersbackpack:travelersbackpack_entity
	at nerdhub.cardinal.components.api.ComponentType.get(ComponentType.java:109)
	at com.tiviacz.travelersbackpack.component.ComponentUtils.isWearingBackpack(ComponentUtils.java:78)
	at com.tiviacz.travelersbackpack.client.renderer.TravelersBackpackEntityFeature.render(TravelersBackpackEntityFeature.java:34)
	at com.tiviacz.travelersbackpack.client.renderer.TravelersBackpackEntityFeature.method_4199(TravelersBackpackEntityFeature.java:20)
	at net.minecraft.class_922.method_4054(class_922.java:139)
	at net.minecraft.class_927.method_4072(class_927.java:43)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:261)
	at net.minecraft.class_761.method_22977(class_761.java:1459)
	at net.minecraft.class_761.method_22710(class_761.java:1219)
	at net.minecraft.class_757.method_3188(class_757.java:727)
	at net.minecraft.class_757.method_3192(class_757.java:546)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

## Steps to reproduce

In any world try to spawn a brute piglin nearby. You can do this by using the spawn egg or meet them naturally in bastion remnant.

## Expected behavior 

Mobs are spawned/rendered OK and the game doesn't crash.

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric/files fixed
