### ISSUE TITLE
Crash: Viewing backpack content pressing CTRL freezes and closes the game.

### ISSUE THREAD

**Issue by Victor-ARC** [Tiviacz1337/Travelers-Backpack#672]
### General Information
System: Windows 11
Processor: Intel i7 13th Gen
Graphics: Nvidia GeForce 3060Ti (dedicated) 12gb VRAM GDDR5
RAM: 32 GB DDR4

### Game Information
Client: Minecraft 1.20.1
Java: Bundled.
Modloader : Forge 47.1.0 
JVM Args: `-Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Duser.timezone=GMT-6`
Modlist:
```
client-1.20.1-20230612.114412-srg.jar              |minecraft          |1.20.1              
easy_mob_farm_1.20.1-5.3.1.jar                     |easy_mob_farm      |5.3.1                
inventorysorter-23.0.0.jar                         |inventorysorter    |23.0.0               
clienttweaks-forge-1.20-11.0.0.jar                 |clienttweaks       |11.0.0               
MouseTweaks-forge-mc1.20-2.25.jar                  |mousetweaks        |2.25                 
EasyAnvils-v8.0.0-1.20.1-Forge.jar                 |easyanvils         |8.0.0               
trashslot-forge-1.20-15.0.0.jar                    |trashslot          |15.0.0               
Jade-1.20-forge-11.1.4.jar                         |jade               |11.1.4               
ColaMixinConfig-v1.0.2.jar                         |caffeineconfig     |1.0.2                
material_elements_1.20.1-7.1.0.jar                 |material_elements  |7.1.0                
EasyMagic-v8.0.0-1.20.1-Forge.jar                  |easymagic          |8.0.0               
ash_api-forge-3.0.0+1.20.1.jar                     |ash_api            |3.0.0+1.20.1         
jei-1.20.1-forge-15.2.0.23.jar                     |jei                |15.2.0.23            
flourish-forge-3.0.0+1.20.1.jar                    |flourish           |3.0.0+1.20.1         
domum_ornamentum-1.20-1.0.104-ALPHA-universal.jar  |domum_ornamentum   |1.20-1.0.104-ALPHA   
justmobheads-1.20.1-7.3.jar                        |justmobheads       |7.3                  
easy_villagers-1.20.1-1.0.11.jar                   |easy_villagers     |1.20.1-1.0.11        
rubidium-0.6.5.jar                                 |rubidium           |0.6.5                
corail_woodcutter-1.20.1-3.0.1.jar                 |corail_woodcutter  |3.0.1                
blockui-1.20-0.0.84-ALPHA.jar                      |blockui            |1.20-0.0.84-ALPHA    
Xaeros_Minimap_23.5.0_Forge_1.20.jar               |xaerominimap       |23.5.0               
waystones-forge-1.20-14.0.1.jar                    |waystones          |14.0.1               
oculus-mc1.20-1.6.4.jar                            |oculus             |1.6.4                
rubidium-extra-0.4.20+mc1.20-build.91.jar          |sodiumextra        |0.4.20+mc1.20-build. 
collective-1.20.1-6.65.jar                         |collective         |6.65                 
Clumps-forge-1.20.1-12.0.0.3.jar                   |clumps             |12.0.0.3             
XaerosWorldMap_1.30.6_Forge_1.20.jar               |xaeroworldmap      |1.30.6               
TravelersBackpack-1.20.1-9.1.4.jar                 |travelersbackpack  |9.1.4                
NaturesCompass-1.20.1-1.11.1-forge.jar             |naturescompass     |1.0.0                
SereneSeasons-1.20.1-9.0.0.43.jar                  |sereneseasons      |9.0.0.43             
invhud.forge.1.20.1-3.4.15.jar                     |inventoryhud       |3.4.15               
structurize-1.20-1.0.584-BETA.jar                  |structurize        |1.20-1.0.584-BETA    
multipiston-1.20-1.2.31-ALPHA.jar                  |multipiston        |1.20-1.2.31-ALPHA    
minecolonies-1.20.1-1.1.8-ALPHA.jar                |minecolonies       |1.20.1-1.1.8-ALPHA   
seasonhud-1.20.1-1.4.20.jar                        |seasonhud          |1.4.20               
balm-forge-1.20-7.0.4.jar                          |balm               |7.0.4                
PuzzlesLib-v8.0.7-1.20.1-Forge.jar                 |puzzleslib         |8.0.7               
FallingTree-1.20.1-4.2.0.jar                       |fallingtree        |4.2.0               
cloth-config-11.1.106-forge.jar                    |cloth_config       |11.1.106             
forge-1.20.1-47.1.0-universal.jar                  |forge              |47.1.0              
stackrefill-1.20.1-4.0.jar                         |stackrefill        |4.0                  
JadeColonies-1.20.1-1.4.1.jar                      |jadecolonies       |1.4.1                
easy_piglins-1.20.1-1.0.1.jar                      |easy_piglins       |1.20.1-1.0.1 
```

### Bug Information
Description: While trying to view the contents of a backpack, the game crashes. The tooltip says, “press CTRL to see contents”, once pressed, the game freezes and then closes. The backpack is empty except for the fluid tanks (filled with water).
Error shown:
```
The game crashed whilst rendering screen
Error: java.lang.RuntimeException: Slot 39 not in valid range - [0,37)
```
Stacktrace (from crash report): 
```
Description: Rendering screen

java.lang.RuntimeException: Slot 39 not in valid range - [0,37)
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:206) ~[forge-1.20.1-47.1.0-universal.jar%23241!/:?] {re:classloading}
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:58) ~[forge-1.20.1-47.1.0-universal.jar%23241!/:?] {re:classloading}
	at com.tiviacz.travelersbackpack.client.screens.tooltip.BackpackTooltipComponent.hasToolInSlot(BackpackTooltipComponent.java:83) ~[TravelersBackpack-1.20.1-9.1.4.jar%23232!/:1.20.1-9.1.4] {re:classloading}
	at com.tiviacz.travelersbackpack.client.screens.tooltip.ClientBackpackTooltipComponent.m_183452_(ClientBackpackTooltipComponent.java:101) ~[TravelersBackpack-1.20.1-9.1.4.jar%23232!/:1.20.1-9.1.4] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.GuiGraphics.m_280497_(GuiGraphics.java:625) ~[client-1.20.1-20230612.114412-srg.jar%23236!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.GuiGraphics.m_280677_(GuiGraphics.java:558) ~[client-1.20.1-20230612.114412-srg.jar%23236!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.GuiGraphics.renderTooltip(GuiGraphics.java:552) ~[client-1.20.1-20230612.114412-srg.jar%23236!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.AbstractContainerScreen.m_280072_(AbstractContainerScreen.java:163) ~[client-1.20.1-20230612.114412-srg.jar%23236!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:mousetweaks.mixins.json:AbstractContainerScreenAccessor,pl:mixin:APP:balm.mixins.json:AbstractContainerScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.inventory.InventoryScreen.m_88315_(InventoryScreen.java:80) ~[client-1.20.1-20230612.114412-srg.jar%23236!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.Screen.m_280264_(Screen.java:109) ~[client-1.20.1-20230612.114412-srg.jar%23236!/:?] {re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:ScreenAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:423) ~[forge-1.20.1-47.1.0-universal.jar%23241!/:?] {re:mixin,re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:416) ~[forge-1.20.1-47.1.0-universal.jar%23241!/:?] {re:mixin,re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:965) ~[client-1.20.1-20230612.114412-srg.jar%23236!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23236!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23236!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:rubidium.mixins.json:core.MixinMinecraftClient,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Keybinds,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_Images,pl:mixin:APP:mixins.oculus.json:MixinMinecraft_PipelineManagement,pl:mixin:APP:sodium-extra.mixins.json:gui.MinecraftClientAccessor,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.1.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.1.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

```
Additional information: I noticed that the contents of the backpack are not lost. I removed the items just to be safe, but so far, the liquids remain there and a few blocks I missed once. Moreover, this happened both without, before, and after upgrading the backpack. That means, Leather, Iron, and Diamond Tiers.

**Comment by Tiviacz1337** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/travelers-backpack/files/all
https://modrinth.com/mod/travelersbackpack/versions
Fixed
