### ISSUE TITLE
game crashes + unplayable when placed backpack

### ISSUE THREAD

**Issue by lillcait** [Tiviacz1337/Travelers-Backpack#676]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

forge version 1.19 - 8.0.8 jar

1. Describe the bug 

i placed my cactus backpack on the ground and it crashed my game, im now unable to play my my game as everytime i load in next to the placed backpack it freezes completely crashes again - my backpack has modded and unmodded items within it 

2. Write steps to reproduce the bug

place cactus backpack with some items in on the ground - thats all i did

3. What is expected behaviour 

your game will freeze and then crash after 3 seconds or so 

4. Screenshots (If applicable)

![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/122820317/6b8f262f-e7d8-4f47-a567-c2a574dbc678)

CRASH REPORT:

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 7/22/23, 3:10 PM
Description: Ticking block entity

java.lang.AbstractMethodError: Receiver class com.tiviacz.travelersbackpack.blockentity.TravelersBackpackBlockEntity does not define or inherit an implementation of the resolved method 'abstract net.minecraft.world.level.Level getLevel()' of interface com.tiviacz.travelersbackpack.inventory.ITravelersBackpackContainer.
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.cactusAbility(BackpackAbilities.java:349) ~[TravelersBackpack-1.19-8.0.8.jar%23196!/:1.19-8.0.8] {re:classloading}
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.abilityTick(BackpackAbilities.java:155) ~[TravelersBackpack-1.19-8.0.8.jar%23196!/:1.19-8.0.8] {re:classloading}
	at com.tiviacz.travelersbackpack.blockentity.TravelersBackpackBlockEntity.tick(TravelersBackpackBlockEntity.java:545) ~[TravelersBackpack-1.19-8.0.8.jar%23196!/:1.19-8.0.8] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:330) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:245) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.cactusAbility(BackpackAbilities.java:349) ~[TravelersBackpack-1.19-8.0.8.jar%23196!/:1.19-8.0.8] {re:classloading}
	at com.tiviacz.travelersbackpack.common.BackpackAbilities.abilityTick(BackpackAbilities.java:155) ~[TravelersBackpack-1.19-8.0.8.jar%23196!/:1.19-8.0.8] {re:classloading}
	at com.tiviacz.travelersbackpack.blockentity.TravelersBackpackBlockEntity.tick(TravelersBackpackBlockEntity.java:545) ~[TravelersBackpack-1.19-8.0.8.jar%23196!/:1.19-8.0.8] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:330) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:A}
-- Block entity being ticked --
Details:
	Name: travelersbackpack:travelers_backpack // com.tiviacz.travelersbackpack.blockentity.TravelersBackpackBlockEntity
	Block: Block{travelersbackpack:cactus}[facing=north]
	Block location: World: (1055,67,-528), Section: (at 15,3,0 in 65,4,-33; chunk contains blocks 1040,-64,-528 to 1055,319,-513), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,-64,-1024 to 1535,319,-513)
	Block: Block{travelersbackpack:cactus}[facing=north]
	Block location: World: (1055,67,-528), Section: (at 15,3,0 in 65,4,-33; chunk contains blocks 1040,-64,-528 to 1055,319,-513), Region: (2,-2; contains chunks 64,-64 to 95,-33, blocks 1024,-64,-1024 to 1535,319,-513)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:687) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:780) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:446) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:330) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:245) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['lillcait'/133, l='ServerLevel[no]', x=1055.50, y=67.00, z=-529.50]]
	Chunk stats: 4372
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,98,0), Section: (at 0,2,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 1370755 game time, 677167 day time
	Level name: no
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 8334 (now: false), thunder time: 107736 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:245) ~[client-1.19-20220607.102129-srg.jar%23200!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin}

**Comment by Tiviacz1337** [comment]
1.19 is not supported
