### ISSUE TITLE
Items lost in forge server on 1.19.2

### ISSUE THREAD

**Issue by ISNing** [Tiviacz1337/Travelers-Backpack#691]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Minecraft 1.19.2 Forge 43.2.17 with Mohist Server
Mod version: 1.19.2-8.2.30

1. Describe the bug 
Items randomly disappear when putting anything into backpack

Log printed in server when losting things:
```
[21:26:17 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundContainerClickPacket@d22a5b6, suppressing error
net.minecraft.ReportedException: Container click
        at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:376) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at com.tiviacz.travelersbackpack.inventory.menu.TravelersBackpackBaseMenu.m_150399_(TravelersBackpackBaseMenu.java:705) ~[TravelersBackpack-1.19.2-8.2.30.jar%23217!/:1.19.2-8.2.30]
        at com.tiviacz.travelersbackpack.inventory.menu.TravelersBackpackItemMenu.m_150399_(TravelersBackpackItemMenu.java:89) ~[TravelersBackpack-1.19.2-8.2.30.jar%23217!/:1.19.2-8.2.30]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerGamePacketListenerImpl.java:1739) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:25) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:901) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:171) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:884) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:878) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:864) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:795) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:278) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.inventory.InventoryView.convertSlot(int)" because "what" is null
        at org.bukkit.event.inventory.InventoryDragEvent.<init>(InventoryDragEvent.java:77) ~[forge-1.19.2-43.2.14-universal.jar%23228!/:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:445) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:362) ~[server-1.19.2-20220805.130853-srg.jar%23223!/:?]
        ... 19 more
```

2. Write steps to reproduce the bug
Install this mod on mohist server(I don't know whether this occur on other servers, if you know, please tell me)
Connect to this server
Put any thing into a backpack
it will disappear and can be found no where

3. What is expected behaviour 
Items should be seen in the backpack

**Comment by Tiviacz1337** [comment]
do you use spigot?

**Comment by ISNing** [comment]
No, I didn't try it on other server

**Comment by Tiviacz1337** [comment]
the logs say there's something wrong with bukkit, traveler's backpack does not support bukkit only forge
