### ISSUE TITLE
Fabric Building Wands Incompat?

### ISSUE THREAD

**Issue by Landon-9999** [Tiviacz1337/Travelers-Backpack#719]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
[main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.22
- fabric-api 0.76.1+1.19.2
- travelersbackpack 1.19.2-8.2.28
	   \-- reach-entity-attributes 2.3.0
- wands 2.6.8-release
https://modrinth.com/mod/building-wands

1. Describe the bug 
Crash when rendering backpack gui with a fabric building wand inside the backpack.

2. Write steps to reproduce the bug
Open a backpack and put in a building wand. More specifically I do have a pickaxe inside the building wand so it is rendering a 1 on the item icon.

3. What is expected behaviour 
Render the gui without crashing

4. Relevant log lines
```
[12:49:02] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_327.method_1727(String)" because "font" is null
	at net.minecraft.class_918.handler$ipl001$wands$renderGuiItemDecorations(class_918.java:10588) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_4022(class_918.java:422) ~[client-intermediary.jar:?]
	at net.minecraft.class_918.method_4025(class_918.java:366) ~[client-intermediary.jar:?]
	at com.tiviacz.travelersbackpack.client.screen.OverlayHandledScreen.drawItemStack(OverlayHandledScreen.java:123) ~[travelers-backpack-1.19.2-8.2.28.jar:?]
	at com.tiviacz.travelersbackpack.client.screen.OverlayHandledScreen.renderOverlay(OverlayHandledScreen.java:69) ~[travelers-backpack-1.19.2-8.2.28.jar:?]
	at net.minecraft.class_329.handler$ing001$travelersbackpack$renderOverlay(class_329.java:12987) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1759(class_329.java:611) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:204) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:862) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.22.jar:?]

```

**Comment by Tiviacz1337** [comment]
![image](https://github.com/Tiviacz1337/Travelers-Backpack/assets/34790800/f4a4bb6a-aba6-4950-9eed-1f3498fcd3b4)
works for me without problems

**Comment by Landon-9999** [comment]
Oh I forgot to mention that I had a tool equipped inside of the building wand. That's when it renders a number on the wand icon and crashes inside the backpack for some reason. Also had some durability missing on the wand itself if that matters any.

**Comment by Tiviacz1337** [comment]
how to put tool inside?

**Comment by Landon-9999** [comment]
I think you have to set the keybind for the wand menu or whatever it is called. Then you can put a pickaxe in there

**Comment by Tiviacz1337** [comment]
I've put iteems in the wand and still no crash, althrough the number next to the wand is not visible on overlay

**Comment by Landon-9999** [comment]
I will have to see if the latest update for 1.19.2 solves the issue. Tried it with just the backpack mod and the building wand mod and it worked. But I'll try in my modpack next week and see if it still crashes
