### ISSUE TITLE
encountered error during sided_setup 

### ISSUE THREAD

**Issue by McFireWolf** [Tiviacz1337/Travelers-Backpack#722]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Forge 1.19.4
Mod version 1.19.4-8.4.16

1. Describe the bug 
Game give the error when starting the game, unknown cause

2. Write steps to reproduce the bug
Have travelers backpack in the mods folder, launch game

3. What is expected behaviour 
Game should start normally, without the error

4. Screenshots (If applicable)
![Screenshot (36)](https://github.com/Tiviacz1337/Travelers-Backpack/assets/61443684/f378e6ef-7932-4a0f-8ca0-69c3f74f6692)

Only started when I added the enchantment infuser mod, and I get the same error each time. But even if I remopve the enchantment infuser and start the game, it persists. I got it to work by removing TB from my folder and reloading the world, and then putting TB back in. The problem is I lost the backpack and all the items within it, and when I exited minecraft and tried to load again later, the issue came back. i really dont wanna have to do this each time. i have also tried using different versions of the mod, to no avail

**Comment by Tiviacz1337** [comment]
can you show the crash?

**Comment by McFireWolf** [comment]
---- Minecraft Crash Report ----
// My bad.

Time: 2023-10-14 16:54:40
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:58) ~[forge-1.19.4-45.2.0-universal.jar%23217!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:165) ~[forge-1.19.4-45.2.0-universal.jar%23217!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:577) ~[client-1.19.4-20230314.122934-srg.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:582) ~[client-1.19.4-20230314.122934-srg.jar%23212!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:571) ~[client-1.19.4-20230314.122934-srg.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_86412_(LoadingOverlay.java:196) ~[client-1.19.4-20230314.122934-srg.jar%23212!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1363) ~[client-1.19.4-20230314.122934-srg.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1148) ~[client-1.19.4-20230314.122934-srg.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:719) ~[client-1.19.4-20230314.122934-srg.jar%23212!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[1.19.4-forge-45.2.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.4-45.2.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?] {re:mixin}
-- MOD travelersbackpack --
Details:
	Mod File: /C:/Users/robro/AppData/Roaming/.minecraft/mods/TravelersBackpack-1.19.4-8.4.17.jar
	Failure message: Traveler's Backpack (travelersbackpack) encountered an error during the sided_setup event phase
		java.util.ConcurrentModificationException: null
	Mod Version: 8.4.17
	Mod Issue URL: NOT PROVIDED
	Exception message: java.util.ConcurrentModificationException
Stacktrace:
	at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?] {re:mixin}
	at net.minecraft.client.renderer.item.ItemProperties.register(ItemProperties.java:65) ~[client-1.19.4-20230314.122934-srg.jar%23212!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at com.tiviacz.travelersbackpack.handlers.ModClientEventHandler.registerItemModelProperty(ModClientEventHandler.java:30) ~[TravelersBackpack-1.19.4-8.4.17.jar%23206!/:1.19.4-8.4.17] {re:classloading}
	at com.tiviacz.travelersbackpack.TravelersBackpack.doClientStuff(TravelersBackpack.java:94) ~[TravelersBackpack-1.19.4-8.4.17.jar%23206!/:1.19.4-8.4.17] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19.4-45.2.0.jar%23214!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:122) ~[fmlcore-1.19.4-45.2.0.jar%23213!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.19.4
	Minecraft Version ID: 1.19.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2074608008 bytes (1978 MiB) / 3489660928 bytes (3328 MiB) up to 34359738368 bytes (32768 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.80
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon RX 5700 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: DriverVersion=31.0.12027.9001
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 68205.88
	Virtual memory used (MB): 18156.24
	Swap memory total (MB): 2772.34
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx32G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	OptiFine Version: OptiFine_1.19.4_HD_U_I4
	OptiFine Build: 20230623-173837
	Render Distance Chunks: 18
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Sildur's+Vibrant+Shaders+v1.51+High.zip
	OpenGlVersion: 3.2.0 Core Profile Context 22.20.27.09.230330
	OpenGlRenderer: AMD Radeon RX 5700 XT
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 16
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.4-45.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.4-45.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.4-45.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.4-45.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.4-45.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		kotori_scala@2.13.10-build-15
		javafml@null
	Mod List: 
		client-1.19.4-20230314.122934-srg.jar             |Minecraft                     |minecraft                     |1.19.4              |ENQUEUE_IM|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		CyclopsCore-1.19.4-1.18.4.jar                     |Cyclops Core                  |cyclopscore                   |1.18.4              |ENQUEUE_IM|Manifest: NOSIGNATURE
		useful_backpacks-1.19.4-1.15.1.112.jar            |Useful Backpacks              |usefulbackpacks               |1.15.1.112          |ENQUEUE_IM|Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		TreeChop-1.19.4-forge-0.18.2.jar                  |HT's TreeChop                 |treechop                      |0.18.2              |ENQUEUE_IM|Manifest: NOSIGNATURE
		CommonCapabilities-1.19.4-2.9.0.jar               |CommonCapabilities            |commoncapabilities            |2.9.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		AmbientSounds_FORGE_v5.2.18_mc1.19.4.jar          |Ambient Sounds                |ambientsounds                 |5.2.18              |ENQUEUE_IM|Manifest: NOSIGNATURE
		EasyAnvils-v6.0.0-1.19.4-Forge.jar                |Easy Anvils                   |easyanvils                    |6.0.0               |ENQUEUE_IM|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		AdditionalEnchantedMiner-1.19.4-1194.2.1.jar      |QuarryPlus                    |quarryplus                    |1194.2.1            |ENQUEUE_IM|Manifest: NOSIGNATURE
		Durability101-forge-1.19.4-0.0.4 (1).jar          |Durability101                 |durability101                 |0.0.4               |ENQUEUE_IM|Manifest: NOSIGNATURE
		ironfurnaces-1.19.4-3.8.0.jar                     |Iron Furnaces                 |ironfurnaces                  |3.8.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		CreativeCore_FORGE_v2.10.22_mc1.19.4.jar          |CreativeCore                  |creativecore                  |2.10.22             |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-fences-1.0.7-mc1.19.4forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.0.7               |ENQUEUE_IM|Manifest: NOSIGNATURE
		EasyMagic-v6.0.0-1.19.4-Forge.jar                 |Easy Magic                    |easymagic                     |6.0.0               |ENQUEUE_IM|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		jei-1.19.4-forge-13.1.0.16.jar                    |Just Enough Items             |jei                           |13.1.0.16           |ENQUEUE_IM|Manifest: NOSIGNATURE
		wthit-forge-7.6.0.jar                             |wthit                         |wthit                         |7.6.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		mcw-windows-2.2.0-mc1.19.4forge.jar               |Macaw's Windows               |mcwwindows                    |2.2.0               |ENQUEUE_IM|Manifest: NOSIGNATURE
		IntegratedDynamics-1.19.4-1.16.7.jar              |IntegratedDynamics            |integrateddynamics            |1.16.7              |ENQUEUE_IM|Manifest: NOSIGNATURE
		journeymap-1.19.4-5.9.7-forge.jar                 |Journeymap                    |journeymap                    |5.9.7               |ENQUEUE_IM|Manifest: NOSIGNATURE
		TravelersBackpack-1.19.4-8.4.17.jar               |Traveler's Backpack           |travelersbackpack             |8.4.17              |ERROR     |Manifest: NOSIGNATURE
		SimpleStorageNetwork-1.19.4-1.9.0.jar             |Simple Storage Network        |storagenetwork                |1.19.4-1.9.0        |ENQUEUE_IM|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		badpackets-forge-0.4.2.jar                        |Bad Packets                   |badpackets                    |0.4.2               |ENQUEUE_IM|Manifest: NOSIGNATURE
		IntegratedTunnels-1.19.4-1.8.20.jar               |IntegratedTunnels             |integratedtunnels             |1.8.20              |ENQUEUE_IM|Manifest: NOSIGNATURE
		u_team_core-forge-1.19.4-5.0.2.261.jar            |U Team Core                   |uteamcore                     |5.0.2.261           |ENQUEUE_IM|Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		PuzzlesLib-v6.0.11-1.19.4-Forge.jar               |Puzzles Lib                   |puzzleslib                    |6.0.11              |ENQUEUE_IM|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		forge-1.19.4-45.2.0-universal.jar                 |Forge                         |forge                         |45.2.0              |ENQUEUE_IM|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		mOres-4.8.4-mc1.19.4.jar                          |mOres                         |mores                         |4.8.4-mc1.19.4      |ENQUEUE_IM|Manifest: NOSIGNATURE
		EnchantingInfuser-v6.0.0-1.19.4-Forge.jar         |Enchanting Infuser            |enchantinginfuser             |6.0.0               |ENQUEUE_IM|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		ironchest-1.19.4-14.3.4.jar                       |Iron Chests                   |ironchest                     |1.19.4-14.3.4       |ENQUEUE_IM|Manifest: NOSIGNATURE
		DungeonsArise-1.19.4-2.1.54-beta.jar              |When Dungeons Arise           |dungeons_arise                |2.1.54-1.19.4       |ENQUEUE_IM|Manifest: NOSIGNATURE
	Crash Report UUID: b385e679-e6e2-4682-a032-2d642ad41609
	FML: 45.2
	Forge: net.minecraftforge:45.2.0

**Comment by Tiviacz1337** [comment]
try regenerate configs or just reinstall minecraft
