### ISSUE TITLE
Fluids in tanks causing game crashes

### ISSUE THREAD

**Issue by IDeletedSystem64** [Tiviacz1337/Travelers-Backpack#724]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric, 1.20.1-1.9.4, 1.20.1-1.9.5

1. Describe the bug 
When a player fills the fluid tanks on their backpack, it causes the client to crash with ``java.lang.IllegalStateException: Not filled all elements of the vertex`` 

2. Write steps to reproduce the bug
Take any of the backpacks, and fill a tank with water

3. What is expected behaviour 
The game continues to run normally

Crashlog: 
https://system64.dev/temp/crash-2023-10_04_16.39.19-client.txt

**Comment by Tiviacz1337** [comment]
check if issue occurs without mine little pony mod

**Comment by JosXa** [comment]
It also happens regularly when the backpack isn't placed, but worn:

```
[26/03/2024 17:45:45 pm] Description: Rendering entity in world
[26/03/2024 17:45:45 pm] 
[26/03/2024 17:45:45 pm] java.lang.IllegalStateException: Not filled all elements of the vertex
[26/03/2024 17:45:45 pm] 	at me.jellysquid.mods.sodium.client.render.vertex.buffer.SodiumBufferBuilder.method_1344(SodiumBufferBuilder.java:299)
[26/03/2024 17:45:45 pm] 	at com.tiviacz.travelersbackpack.util.RenderUtils.renderFluidSides(RenderUtils.java:149)
[26/03/2024 17:45:45 pm] 	at com.tiviacz.travelersbackpack.util.RenderUtils.renderFluidInTank(RenderUtils.java:174)
[26/03/2024 17:45:45 pm] 	at com.tiviacz.travelersbackpack.client.renderer.FluidPart.render(FluidPart.java:40)
[26/03/2024 17:45:45 pm] 	at com.tiviacz.travelersbackpack.client.renderer.FluidPart.method_22698(FluidPart.java:29)
[26/03/2024 17:45:45 pm] 	at com.tiviacz.travelersbackpack.client.model.TravelersBackpackWearableModel.method_2828(TravelersBackpackWearableModel.java:169)
```
