### ISSUE TITLE
crash went click backapack frozen Slot 39 not in valid range - [0,21)

### ISSUE THREAD

**Issue by mrdragonblack** [Tiviacz1337/Travelers-Backpack#734]
Error rendering overlay 'travelersbackpack:travelers_backpack'
java.lang.RuntimeException: Slot 39 not in valid range - [0,21)
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:206) ~[forge-1.19.2-43.3.2-universal.jar%23212!/:?]
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:58) ~[forge-1.19.2-43.3.2-universal.jar%23212!/:?]
	at com.tiviacz.travelersbackpack.client.screens.OverlayScreen.renderOverlay(OverlayScreen.java:56) ~[TravelersBackpack-1.19.2-8.2.6_2.jar%23204!/:1.19.2-8.2.6]
	at com.tiviacz.travelersbackpack.handlers.ModClientEventsHandler.lambda$registerOverlay$0(ModClientEventsHandler.java:51) ~[TravelersBackpack-1.19.2-8.2.6_2.jar%23204!/:1.19.2-8.2.6]
	at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:141) ~[forge-1.19.2-43.3.2-universal.jar%23212!/:?]
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%23121!/:?]
	at net.minecraftforge.client.gui.overlay.ForgeGui.m_93030_(ForgeGui.java:136) ~[forge-1.19.2-43.3.2-universal.jar%23212!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1253) ~[client-1.19.2-20220805.130853-srg.jar%23207!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23207!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23207!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23207!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23207!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.2.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
[23:28:36] [Render thread/ERROR]: Exception caught during firing event: Rendering entity in world
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$4411/0x0000000800c7e720@16d241a2
net.minecraft.ReportedException: Rendering entity in world
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:249)
	at TRANSFORMER/paperdoll@1.1.1-mc1.19.1/dev.tr7zw.paperdoll.PaperDollRenderer.drawLivingEntity(PaperDollRenderer.java:190)
	at TRANSFORMER/paperdoll@1.1.1-mc1.19.1/dev.tr7zw.paperdoll.PaperDollRenderer.render(PaperDollRenderer.java:100)
	at TRANSFORMER/paperdoll@1.1.1-mc1.19.1/dev.tr7zw.paperdoll.PaperDollMod.onOverlay(PaperDollMod.java:34)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.3.2/net.minecraftforge.client.gui.overlay.ForgeGui.m_93030_(ForgeGui.java:151)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1253)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.2/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: java.lang.RuntimeException: Slot 39 not in valid range - [0,21)
	at TRANSFORMER/forge@43.3.2/net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:206)
	at TRANSFORMER/forge@43.3.2/net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:58)
	at TRANSFORMER/travelersbackpack@8.2.6/com.tiviacz.travelersbackpack.client.model.StackModelPart.render(StackModelPart.java:32)
	at TRANSFORMER/travelersbackpack@8.2.6/com.tiviacz.travelersbackpack.client.model.TravelersBackpackWearableModel.m_7695_(TravelersBackpackWearableModel.java:179)
	at TRANSFORMER/travelersbackpack@8.2.6/com.tiviacz.travelersbackpack.client.renderer.TravelersBackpackLayer.renderLayer(TravelersBackpackLayer.java:143)
	at TRANSFORMER/travelersbackpack@8.2.6/com.tiviacz.travelersbackpack.client.renderer.TravelersBackpackLayer.render(TravelersBackpackLayer.java:94)
	at TRANSFORMER/travelersbackpack@8.2.6/com.tiviacz.travelersbackpack.client.renderer.TravelersBackpackLayer.m_6494_(TravelersBackpackLayer.java:34)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7392_(LivingEntityRenderer.java:215)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.entity.player.PlayerRenderer.m_7392_(PlayerRenderer.java:61)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.entity.player.PlayerRenderer.m_7392_(PlayerRenderer.java:42)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:186)
	... 26 more

[23:28:36] [Server thread/INFO]: Stopping server
[23:28:36] [Server thread/INFO]: Saving players
[23:28:36] [Server thread/INFO]: Saving worlds
[23:28:37] [Server thread/INFO]: Saving chunks for level 'ServerLevel[survival 1.18.2]'/minecraft:overworld
[23:28:37] [Server thread/INFO]: Saving chunks for level 'ServerLevel[survival 1.18.2]'/minecraft:the_end
[23:28:37] [Server thread/INFO]: Saving chunks for level 'ServerLevel[survival 1.18.2]'/minecraft:the_nether
[23:28:37] [Server thread/INFO]: ThreadedAnvilChunkStorage (survival 1_18_4): All chunks are saved
[23:28:37] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[23:28:37] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[23:28:37] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[23:28:38] [Render thread/INFO]: Finalizing world map session...
[23:28:38] [Thread-4/INFO]: World map cleaned normally!
[23:28:38] [Render thread/INFO]: World map session finalized.
[23:28:38] [Render thread/INFO]: Minimap session finalized.
[23:28:38] [Render thread/INFO]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
[23:28:38] [Render thread/INFO]: JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
[23:28:38] [Render thread/INFO]: Stopping JEI
[23:28:38] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.ReportedException: Rendering entity in world
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:249) ~[client-1.19.2-20220805.130853-srg.jar%23207!/:?]
	at dev.tr7zw.paperdoll.PaperDollRenderer.drawLivingEntity(PaperDollRenderer.java:190) ~[paperdoll-forge-1.1.1-mc1.19.1_2_2.jar%23200!/:1.1.1-mc1.19.1]
	at dev.tr7zw.paperdoll.PaperDollRenderer.render(PaperDollRenderer.java:100) ~[paperdoll-forge-1.1.1-mc1.19.1_2_2.jar%23200!/:1.1.1-mc1.19.1]
	at dev.tr7zw.paperdoll.PaperDollMod.onOverlay(PaperDollMod.java:34) ~[paperdoll-forge-1.1.1-mc1.19.1_2_2.jar%23200!/:1.1.1-mc1.19.1]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?]
	at net.minecraftforge.client.gui.overlay.ForgeGui.m_93030_(ForgeGui.java:151) ~[forge-1.19.2-43.3.2-universal.jar%23212!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1253) ~[client-1.19.2-20220805.130853-srg.jar%23207!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23207!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23207!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23207!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23207!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.2.jar%23101!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.RuntimeException: Slot 39 not in valid range - [0,21)
	at net.minecraftforge.items.ItemStackHandler.validateSlotIndex(ItemStackHandler.java:206) ~[forge-1.19.2-43.3.2-universal.jar%23212!/:?]
	at net.minecraftforge.items.ItemStackHandler.getStackInSlot(ItemStackHandler.java:58) ~[forge-1.19.2-43.3.2-universal.jar%23212!/:?]
	at com.tiviacz.travelersbackpack.client.model.StackModelPart.render(StackModelPart.java:32) ~[TravelersBackpack-1.19.2-8.2.6_2.jar%23204!/:1.19.2-8.2.6]
	at com.tiviacz.travelersbackpack.client.model.TravelersBackpackWearableModel.m_7695_(TravelersBackpackWearableModel.java:179) ~[TravelersBackpack-1.19.2-8.2.6_2.jar%23204!/:1.19.2-8.2.6]
	at com.tiviacz.travelersbackpack.client.renderer.TravelersBackpackLayer.renderLayer(TravelersBackpackLayer.java:143) ~[TravelersBackpack-1.19.2-8.2.6_2.jar%23204!/:1.19.2-8.2.6]
	at com.tiviacz.travelersbackpack.client.renderer.TravelersBackpackLayer.render(TravelersBackpackLayer.java:94) ~[TravelersBackpack-1.19.2-8.2.6_2.jar%23204!/:1.19.2-8.2.6]
	at com.tiviacz.travelersbackpack.client.renderer.TravelersBackpackLayer.m_6494_(TravelersBackpackLayer.java:34) ~[TravelersBackpack-1.19.2-8.2.6_2.jar%23204!/:1.19.2-8.2.6]
	at net.minecraft.client.renderer.entity.LivingEntityRenderer.m_7392_(LivingEntityRenderer.java:215) ~[client-1.19.2-20220805.130853-srg.jar%23207!/:?]
	at net.minecraft.client.renderer.entity.player.PlayerRenderer.m_7392_(PlayerRenderer.java:61) ~[client-1.19.2-20220805.130853-srg.jar%23207!/:?]
	at net.minecraft.client.renderer.entity.player.PlayerRenderer.m_7392_(PlayerRenderer.java:42) ~[client-1.19.2-20220805.130853-srg.jar%23207!/:?]
	at net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114384_(EntityRenderDispatcher.java:186) ~[client-1.19.2-20220805.130853-srg.jar%23207!/:?]
	... 26 more
[23:28:38] [Render thread/FATAL]: Preparing crash report with UUID 7de12a26-1bcd-4575-8c7a-6c79201796ad
[23:28:40] [Render thread/FATAL]: Preparing crash report with UUID aa35bfae-9371-49ba-bdf2-924da35654b7
[23:28:40] [Render thread/FATAL]: Preparing crash report with UUID 75fecb75-1a8d-423a-886b-d6a2d9a7aed6

**Comment by mrdragonblack** [comment]
[crash-2023-10-19_10.02.59-client.txt](https://github.com/Tiviacz1337/Travelers-Backpack/files/13035762/crash-2023-10-19_10.02.59-client.txt)


this is the log crash

**Comment by Tiviacz1337** [comment]
update the mod to latest version
