### ISSUE TITLE
Rendering

### ISSUE THREAD

**Issue by DemonnoLex** [Tiviacz1337/Travelers-Backpack#797]
Quilt/fabric 1.19.2-8.2.33

Opening the UI crashes my game.

I would press the key binding to pull up the UI ( ; in my case) then my game crashes

When I press the key to bring up the UI the UI should pull up.

I don't have screenshots but I do have the crash report.

---- Minecraft Crash Report ----
// There are four lights!

Time: 2023-12-30 13:35:49
Description: Rendering item

java.lang.NullPointerException: Cannot load from object array because "ladysnake.ratsmischief.client.render.entity.PartyHatFeatureRenderer.TEXTURES" is null
	at ladysnake.ratsmischief.client.render.item.RatItemRenderer.render(RatItemRenderer.java:74)
	at ladysnake.ratsmischief.client.render.item.RatItemRenderer.render(RatItemRenderer.java:21)
	at software.bernie.geckolib3.renderers.geo.GeoItemRenderer.render(GeoItemRenderer.java:123)
	at net.minecraft.class_756.handler$eef000$quilted_fabric_rendering_v1$fabric_onRender(class_756.java:1042)
	at net.minecraft.class_756.method_3166(class_756.java)
	at net.minecraft.class_918.method_23179(class_918.java:133)
	at net.minecraft.class_918.method_4021(class_918.java:307)
	at net.minecraft.class_918.method_4026(class_918.java:350)
	at net.minecraft.class_918.method_36543(class_918.java:340)
	at net.minecraft.class_918.method_27951(class_918.java:336)
	at net.minecraft.class_465.method_2385(class_465.java:264)
	at net.minecraft.class_465.method_25394(class_465.java:122)
	at com.tiviacz.travelersbackpack.client.screen.TravelersBackpackHandledScreen.method_25394(TravelersBackpackHandledScreen.java:162)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551)
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84)
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by Tiviacz1337** [comment]
report to  Rat's Mischief
