### ISSUE TITLE
When I lunch my Minecraft server with the traveler's backpack mod it crashes for some reason can anyone help?

### ISSUE THREAD

**Issue by YoussefKarim** [Tiviacz1337/Travelers-Backpack#800]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
hi my server is working on 1.16.5-0.15.13 fabric
and the traveler's backpack mod version [1.16.5-5.4.38] fabric

1. Describe the bug 
when I start the server It crashes for some reason I am not sure why I tried reading the log but I couldn't understand,
I hope any of the devs here can help me solve this problem.

here is the log if ya'll want to read it

log :
<html>
<body>

[12:06:29] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.15.3
--
2 | [12:06:30] [main/INFO]: Loading 60 mods:
3 | - cardinal-components 2.8.3
4 | \|-- cardinal-components-base 2.8.3
5 | \|-- cardinal-components-block 2.8.3
6 | \|-- cardinal-components-chunk 2.8.3
7 | \|-- cardinal-components-entity 2.8.3
8 | \|-- cardinal-components-item 2.8.3
9 | \|-- cardinal-components-level 2.8.3
10 | \|-- cardinal-components-scoreboard 2.8.3
11 | \|-- cardinal-components-util 2.8.3
12 | \-- cardinal-components-world 2.8.3
13 | - cloth-api 1.6.59
14 | \|-- cloth-armor-api-v1 1.6.59
15 | \|-- cloth-client-events-v0 1.6.59
16 | \|-- cloth-common-events-v1 1.6.59
17 | \|-- cloth-datagen-api-v1 1.6.59
18 | \|-- cloth-durability-bar-api-v1 1.6.59
19 | \|-- cloth-dynamic-registry-api-v1 1.6.59
20 | \|-- cloth-scissors-api-v1 1.6.59
21 | \-- cloth-utils-v1 1.6.59
22 | - cloth-config2 4.17.101
23 | \-- cloth-basic-math 0.6.1
24 | - fabric 0.42.0+1.16
25 | \|-- fabric-api-base 0.4.0+3cc0f0907d
26 | \|-- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d
27 | \|-- fabric-biome-api-v1 3.1.13+3cc0f0907d
28 | \|-- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d
29 | \|-- fabric-command-api-v1 1.1.3+3cc0f0907d
30 | \|-- fabric-commands-v0 0.2.3+3cc0f0907d
31 | \|-- fabric-containers-v0 0.1.12+3cc0f0907d
32 | \|-- fabric-content-registries-v0 0.2.5+3cc0f0907d
33 | \|-- fabric-crash-report-info-v1 0.1.4+3cc0f0907d
34 | \|-- fabric-dimensions-v1 2.0.8+3cc0f0907d
35 | \|-- fabric-entity-events-v1 1.2.4+3cc0f0907d
36 | \|-- fabric-events-interaction-v0 0.4.5+3cc0f0907d
37 | \|-- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d
38 | \|-- fabric-game-rule-api-v1 1.0.7+3cc0f0907d
39 | \|-- fabric-item-api-v1 1.2.2+3cc0f0907d
40 | \|-- fabric-item-groups-v0 0.3.1+3cc0f0907d
41 | \|-- fabric-key-binding-api-v1 1.0.5+3cc0f0907d
42 | \|-- fabric-keybindings-v0 0.2.2+3cc0f0907d
43 | \|-- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d
44 | \|-- fabric-loot-tables-v1 1.0.3+3cc0f0907d
45 | \|-- fabric-mining-levels-v0 0.1.4+3cc0f0907d
46 | \|-- fabric-models-v0 0.3.1+3cc0f0907d
47 | \|-- fabric-networking-api-v1 1.0.5+3cc0f0907d
48 | \|-- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d
49 | \|-- fabric-networking-v0 0.3.3+3cc0f0907d
50 | \|-- fabric-object-builder-api-v1 1.9.6+3cc0f0907d
51 | \|-- fabric-object-builders-v0 0.7.3+3cc0f0907d
52 | \|-- fabric-particles-v1 0.2.5+3cc0f0907d
53 | \|-- fabric-registry-sync-v0 0.7.6+3cc0f0907d
54 | \|-- fabric-renderer-api-v1 0.4.5+3cc0f0907d
55 | \|-- fabric-renderer-indigo 0.4.5+3cc0f0907d
56 | \|-- fabric-renderer-registries-v1 2.3.1+3cc0f0907d
57 | \|-- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d
58 | \|-- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d
59 | \|-- fabric-rendering-v0 1.1.3+3cc0f0907d
60 | \|-- fabric-rendering-v1 1.6.1+3cc0f0907d
61 | \|-- fabric-resource-loader-v0 0.4.8+3cc0f0907d
62 | \|-- fabric-screen-api-v1 1.0.1+3cc0f0907d
63 | \|-- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d
64 | \|-- fabric-structure-api-v1 1.1.12+3cc0f0907d
65 | \|-- fabric-tag-extensions-v0 1.1.2+3cc0f0907d
66 | \|-- fabric-textures-v0 1.0.7+3cc0f0907d
67 | \|-- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d
68 | \-- fabric-transfer-api-v1 1.5.0+3cc0f0907d
69 | - fabricloader 0.15.3
70 | \-- mixinextras 0.3.2
71 | - java 8
72 | - minecraft 1.16.5
73 | - travelersbackpack 1.16.5-5.4.38
74 | \-- reach-entity-attributes 1.1.1
75 | [12:06:30] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/server/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
76 | [12:06:31] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
77 | [12:06:37] [main/INFO]: Registered the FluidEffect with Unique ID of minecraft:water for minecraft:water 81000 with the ID 0
78 | [12:06:37] [main/INFO]: Registered the FluidEffect with Unique ID of minecraft:lava for minecraft:lava 81000 with the ID 1
79 | [12:06:37] [main/INFO]: Registered the FluidEffect with Unique ID of travelersbackpack:potion for travelersbackpack:potion_still 27000 with the ID 2
80 | [12:06:37] [main/INFO]: Registered the FluidEffect with Unique ID of travelersbackpack:milk for travelersbackpack:milk_still 81000 with the ID 3
81 | [12:06:38] [main/INFO]: Starting datagen in: /src/generated/resources
82 | [12:06:38] [main/FATAL]: Failed to start the minecraft server
83 | java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'travelersbackpack'!
84 | at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.3.jar:?]
85 | at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.3.jar:?]
86 | at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.3.jar:?]
87 | at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.3.jar:?]
88 | at net.minecraft.server.Main.main(Main.java:92) [server-intermediary.jar:?]
89 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.3.jar:?]
90 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.3.jar:?]
91 | at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.3.jar:?]
92 | at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.3.jar:?]
93 | Caused by: java.lang.RuntimeException: java.nio.file.AccessDeniedException: /src
94 | at me.shedaniel.cloth.impl.datagen.DataGeneratorHandlerImpl.run(DataGeneratorHandlerImpl.java:87) ~[cloth-datagen-api-v1-1.6.59-143cf2b0f38ba42.jar:?]
95 | at com.tiviacz.travelersbackpack.datagen.ModRecipesProvider.generate(ModRecipesProvider.java:37) ~[travelers-backpack-1.16.5-5.4.38.jar:?]
96 | at com.tiviacz.travelersbackpack.TravelersBackpack.onInitialize(TravelersBackpack.java:67) ~[travelers-backpack-1.16.5-5.4.38.jar:?]
97 | at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
98 | ... 6 more
99 | Caused by: java.nio.file.AccessDeniedException: /src
100 | at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:1.8.0_392]
101 | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_392]
102 | at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_392]
103 | at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:1.8.0_392]
104 | at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_392]
105 | at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_392]
106 | at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_392]
107 | at net.minecraft.class_2408.<init>(class_2408.java:37) ~[server-intermediary.jar:?]
108 | at net.minecraft.class_2403.method_10315(class_2403.java:40) ~[server-intermediary.jar:?]
109 | at me.shedaniel.cloth.impl.datagen.DataGeneratorHandlerImpl.run(DataGeneratorHandlerImpl.java:85) ~[cloth-datagen-api-v1-1.6.59-143cf2b0f38ba42.jar:?]
110 | at com.tiviacz.travelersbackpack.datagen.ModRecipesProvider.generate(ModRecipesProvider.java:37) ~[travelers-backpack-1.16.5-5.4.38.jar:?]
111 | at com.tiviacz.travelersbackpack.TravelersBackpack.onInitialize(TravelersBackpack.java:67) ~[travelers-backpack-1.16.5-5.4.38.jar:?]
112 | at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
113 | ... 6 more

</body>
</html>

2. Write steps to reproduce the bug
I tried everything I could think of but I couldn't do anything at the end.
sorry but I tried my best.

3. What is expected behaviour 
I would love for someone help I want this mod to work so I and my friends could play together I really enjoyed this mod and I would prefer adding it to my friend's server

4. Screenshots (If applicable)
[12:06:29] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.15.3
[1[2](https://aternos.org/log/#L2):06:30] [main/INFO]: Loading 60 mods:
	- cardinal-components 2.8.3
	   |-- cardinal-components-base 2.8.3
	   |-- cardinal-components-block 2.8.3
	   |-- cardinal-components-chunk 2.8.3
	   |-- cardinal-components-entity 2.8.3
	   |-- cardinal-components-item 2.8.3
	   |-- cardinal-components-level 2.8.3
	   |-- cardinal-components-scoreboard 2.8.3
	   |-- cardinal-components-util 2.8.3
	   \-- cardinal-components-world 2.8.3
	- cloth-api 1.6.59
	   |-- cloth-armor-api-v1 1.6.59
	   |-- cloth-client-events-v0 1.6.59
	   |-- cloth-common-events-v1 1.6.59
	   |-- cloth-datagen-api-v1 1.6.59
	   |-- cloth-durability-bar-api-v1 1.6.59
	   |-- cloth-dynamic-registry-api-v1 1.6.59
	   |-- cloth-scissors-api-v1 1.6.59
	   \-- cloth-utils-v1 1.6.59
	- cloth-config2 4.17.101
	   \-- cloth-basic-math 0.6.1
	- fabric 0.42.0+1.16
	   |-- fabric-api-base 0.4.0+3cc0f0907d
	   |-- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d
	   |-- fabric-biome-api-v1 3.1.13+3cc0f0907d
	   |-- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d
	   |-- fabric-command-api-v1 1.1.3+3cc0f0907d
	   |-- fabric-commands-v0 0.2.3+3cc0f0907d
	   |-- fabric-containers-v0 0.1.12+3cc0f0907d
	   |-- fabric-content-registries-v0 0.2.5+3cc0f0907d
	   |-- fabric-crash-report-info-v1 0.1.4+3cc0f0907d
	   |-- fabric-dimensions-v1 2.0.8+3cc0f0907d
	   |-- fabric-entity-events-v1 1.2.4+3cc0f0907d
	   |-- fabric-events-interaction-v0 0.4.5+3cc0f0907d
	   |-- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d
	   |-- fabric-game-rule-api-v1 1.0.7+3cc0f0907d
	   |-- fabric-item-api-v1 1.2.2+3cc0f0907d
	   |-- fabric-item-groups-v0 0.3.1+3cc0f0907d
	   |-- fabric-key-binding-api-v1 1.0.5+3cc0f0907d
	   |-- fabric-keybindings-v0 0.2.2+3cc0f0907d
	   |-- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d
	   |-- fabric-loot-tables-v1 1.0.3+3cc0f0907d
	   |-- fabric-mining-levels-v0 0.1.4+3cc0f0907d
	   |-- fabric-models-v0 0.3.1+3cc0f0907d
	   |-- fabric-networking-api-v1 1.0.5+3cc0f0907d
	   |-- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d
	   |-- fabric-networking-v0 0.3.3+3cc0f0907d
	   |-- fabric-object-builder-api-v1 1.9.6+3cc0f0907d
	   |-- fabric-object-builders-v0 0.7.3+3cc0f0907d
	   |-- fabric-particles-v1 0.2.5+3cc0f0907d
	   |-- fabric-registry-sync-v0 0.7.6+3cc0f0907d
	   |-- fabric-renderer-api-v1 0.4.5+3cc0f0907d
	   |-- fabric-renderer-indigo 0.4.5+3cc0f0907d
	   |-- fabric-renderer-registries-v1 2.3.1+3cc0f0907d
	   |-- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d
	   |-- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d
	   |-- fabric-rendering-v0 1.1.3+3cc0f0907d
	   |-- fabric-rendering-v1 1.6.1+3cc0f0907d
	   |-- fabric-resource-loader-v0 0.4.8+3cc0f0907d
	   |-- fabric-screen-api-v1 1.0.1+3cc0f0907d
	   |-- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d
	   |-- fabric-structure-api-v1 1.1.12+3cc0f0907d
	   |-- fabric-tag-extensions-v0 1.1.2+3cc0f0907d
	   |-- fabric-textures-v0 1.0.7+3cc0f0907d
	   |-- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d
	   \-- fabric-transfer-api-v1 1.5.0+3cc0f0907d
	- fabricloader 0.15.3
	   \-- mixinextras 0.3.2
	- java 8
	- minecraft 1.16.5
	- travelersbackpack 1.16.5-5.4.38
	   \-- reach-entity-attributes 1.1.1
[12:06:30] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/server/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[12:06:[3](https://aternos.org/log/#L3)1] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[12:06:37] [main/INFO]: Registered the FluidEffect with Unique ID of minecraft:water for minecraft:water 81000 with the ID 0
[12:06:37] [main/INFO]: Registered the FluidEffect with Unique ID of minecraft:lava for minecraft:lava 81000 with the ID 1
[12:06:37] [main/INFO]: Registered the FluidEffect with Unique ID of travelersbackpack:potion for travelersbackpack:potion_still 27000 with the ID 2
[12:06:37] [main/INFO]: Registered the FluidEffect with Unique ID of travelersbackpack:milk for travelersbackpack:milk_still 81000 with the ID 3
[12:06:38] [main/INFO]: Starting datagen in: /src/generated/resources
[12:06:38] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'travelersbackpack'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.3.jar:?]
	at net.minecraft.server.Main.main(Main.java:92) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:[4](https://aternos.org/log/#L4)70) [fabric-loader-0.1[5](https://aternos.org/log/#L5).3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.3.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:[6](https://aternos.org/log/#L6)9) [fabric-loader-0.15.3.jar:?]
Caused by: java.lang.RuntimeException: java.nio.file.AccessDeniedException: /src
	at me.shedaniel.cloth.impl.datagen.DataGeneratorHandlerImpl.run(DataGeneratorHandlerImpl.java:8[7](https://aternos.org/log/#L7)) ~[cloth-datagen-api-v1-1.6.59-143cf2b0f3[8](https://aternos.org/log/#L8)ba42.jar:?]
	at com.tiviacz.travelersbackpack.datagen.ModRecipesProvider.generate(ModRecipesProvider.java:37) ~[travelers-backpack-1.16.5-5.4.38.jar:?]
	at com.tiviacz.travelersbackpack.TravelersBackpack.onInitialize(TravelersBackpack.java:67) ~[travelers-backpack-1.16.5-5.4.38.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
	... 6 more
Caused by: java.nio.file.AccessDeniedException: /src
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:1.8.0_3[9](https://aternos.org/log/#L9)2]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:[10](https://aternos.org/log/#L10)2) ~[?:1.8.0_392]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_392]
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:1.8.0_392]
	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_392]
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_392]
	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_392]
	at net.minecraft.class_2408.<init>(class_2408.java:37) ~[server-intermediary.jar:?]
	at net.minecraft.class_2403.method_10315(class_2403.java:40) ~[server-intermediary.jar:?]
	at me.shedaniel.cloth.impl.datagen.DataGeneratorHandlerImpl.run(DataGeneratorHandlerImpl.java:85) ~[cloth-datagen-api-v1-1.6.59-[14](https://aternos.org/log/#L14)3cf2b0f38ba42.jar:?]
	at com.tiviacz.travelersbackpack.datagen.ModRecipesProvider.generate(ModRecipesProvider.java:37) ~[travelers-backpack-1.16.5-5.4.38.jar:?]
	at com.tiviacz.travelersbackpack.TravelersBackpack.onInitialize(TravelersBackpack.java:67) ~[travelers-backpack-1.16.5-5.4.38.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.[15](https://aternos.org/log/#L15).3.jar:?]
	... 6 more

**Comment by Tiviacz1337** [comment]
re-install your server, delete configs etc.
