### ISSUE TITLE
1.19.2 server failing to start due to traveler's backpack

### ISSUE THREAD

**Issue by DigiVore-Programing** [Tiviacz1337/Travelers-Backpack#806]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric version 1.19.2 (loader version 0.15.3) and mod version 8.2.32 

1. Describe the bug 

I have very few mods on this server, but recently (this morning) the server has stopped booting with an error from Travler's Backpack, saying a component is either missing or something happened to the config files.

2. Write steps to reproduce the bug

Unknown, as this happened suddenly.

3. What is expected behaviour 

Server boots and acts as normal, not crashing out due to the backpack mod. 

4. Screenshots (If applicable)
 Failed to load config 'class com.tiviacz.travelersbackpack.config.TravelersBackpackConfigData', using default!
me.shedaniel.autoconfig.serializer.ConfigSerializer$SerializationException: me.shedaniel.cloth.clothconfig.shadowed.blue.endless.jankson.api.SyntaxError: Expected to find '}' to end an object, found EOF instead.
        at me.shedaniel.autoconfig.serializer.JanksonConfigSerializer.deserialize(JanksonConfigSerializer.java:76) ~[cloth-config-8.0.75-d96bc66fbaac6038.jar:?]
        at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:92) ~[cloth-config-8.0.75-d96bc66fbaac6038.jar:?]
        at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53) ~[cloth-config-8.0.75-d96bc66fbaac6038.jar:?]
        at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66) ~[cloth-config-8.0.75-d96bc66fbaac6038.jar:?]
        at com.tiviacz.travelersbackpack.config.TravelersBackpackConfig.setup(TravelersBackpackConfig.java:76) ~[travelers-backpack-1.19.2-8.2.32.jar:?]
        at com.tiviacz.travelersbackpack.TravelersBackpack.onInitialize(TravelersBackpack.java:33) ~[travelers-backpack-1.19.2-8.2.32.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) [fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) [fabric-loader-0.15.3.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.3.jar:?]
Caused by: me.shedaniel.cloth.clothconfig.shadowed.blue.endless.jankson.api.SyntaxError: Expected to find '}' to end an object, found EOF instead.
        at me.shedaniel.cloth.clothconfig.shadowed.blue.endless.jankson.impl.ObjectParserContext.eof(ObjectParserContext.java:136) ~[cloth-config-8.0.75-d96bc66fbaac6038.jar:?]
        at me.shedaniel.cloth.clothconfig.shadowed.blue.endless.jankson.Jankson.load(Jankson.java:173) ~[cloth-config-8.0.75-d96bc66fbaac6038.jar:?]
        at me.shedaniel.cloth.clothconfig.shadowed.blue.endless.jankson.Jankson.load(Jankson.java:79) ~[cloth-config-8.0.75-d96bc66fbaac6038.jar:?]
        at me.shedaniel.autoconfig.serializer.JanksonConfigSerializer.deserialize(JanksonConfigSerializer.java:74) ~[cloth-config-8.0.75-d96bc66fbaac6038.jar:?]
        ... 12 more
[18:42:58] [main/INFO]: Registered the FluidEffect with Unique ID of minecraft:water for minecraft:water 81000 with the ID 0
[18:42:58] [main/INFO]: Registered the FluidEffect with Unique ID of minecraft:lava for minecraft:lava 81000 with the ID 1
[18:42:58] [main/INFO]: Registered the FluidEffect with Unique ID of travelersbackpack:potion for travelersbackpack:potion_still 27000 with the ID 2
[18:42:58] [main/INFO]: Registered the FluidEffect with Unique ID of travelersbackpack:milk for travelersbackpack:milk_still 81000 with the ID 3
[18:42:58] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'origins'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.3.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.3.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.3.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "me.shedaniel.autoconfig.ConfigData.validatePostLoad()" because "this.config" is null
        at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:106) ~[cloth-config-8.0.75-d96bc66fbaac6038.jar:?]
        at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53) ~[cloth-config-8.0.75-d96bc66fbaac6038.jar:?]
        at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66) ~[cloth-config-8.0.75-d96bc66fbaac6038.jar:?]
        at io.github.apace100.origins.Origins.onInitialize(Origins.java:67) ~[Origins-1.19.2-1.7.1.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.3.jar:?]
        ... 6 more

Mod list:

chipped
companion
croptopia
cupboard
entityculling
fabric-api
farmers delight
iris
mob origins
origins
pehkui
resourcefullib
sodium
styled nicknames
travlers-backpack

If any more information is needed, please let me know, I will attach it here.

**Comment by Tiviacz1337** [comment]
remove travelers backpack configs and let it regenerate

**Comment by DigiVore-Programing** [comment]
Did that as a first troubleshooting step, didn't help unfort. I ended up reinstalling the server then transferred the world back over.
