### ISSUE TITLE
Rendering Overlay

### ISSUE THREAD

**Issue by jackyy-chann** [Tiviacz1337/Travelers-Backpack#828]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric 1.20.4-9.4.0.jar

1. Describe the bug 
It wont let me open the game minecraft launcher stops me

2. Write steps to reproduce the bug
Not sure

3. What is expected behaviour 
Game crashing a lot before trying to get in and eventually just not letting me in 

4. Screenshots (If applicable)
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-02-22 21:57:45
Description: Rendering overlay

net.minecraftforge.fml.config.ConfigFileTypeHandler$ConfigLoadingException: Failed loading config file forge-client.toml of type CLIENT for modid forge
      at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:47) ~[fmlcore-1.20.4-49.0.30.jar:?] {}
      at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:60) ~[fmlcore-1.20.4-49.0.30.jar:?] {}
      at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.20.4-49.0.30.jar:?] {}
      at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
      at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?] {}
      at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.20.4-49.0.30.jar:?] {}
      at net.minecraftforge.fml.core.ModStateProvider.lambda$new$1(ModStateProvider.java:67) ~[forge-1.20.4-49.0.30-universal.jar:?] {re:classloading}
      at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.20.4-49.0.30.jar:1.0] {}
      at net.minecraftforge.fml.core.ModStateProvider.lambda$new$3(ModStateProvider.java:66) ~[forge-1.20.4-49.0.30-universal.jar:?] {re:classloading}
      at net.minecraftforge.fml.ModLoader.handleInlineTransition(ModLoader.java:217) ~[fmlcore-1.20.4-49.0.30.jar!/:1.0] {}
      at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$19(ModLoader.java:209) ~[fmlcore-1.20.4-49.0.30.jar!/:1.0] {}
      at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
      at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:209) ~[fmlcore-1.20.4-49.0.30.jar!/:1.0] {}
      at net.minecraftforge.fml.ModLoader.lambda$loadMods$15(ModLoader.java:190) ~[fmlcore-1.20.4-49.0.30.jar!/:1.0] {}
      at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
      at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:190) ~[fmlcore-1.20.4-49.0.30.jar!/:1.0] {}
      at net.minecraftforge.client.loading.ClientModLoader.lambda$startModLoading$5(ClientModLoader.java:80) ~[forge-1.20.4-49.0.30-universal.jar!/:?] {re:classloading,pl:runtimedistcleaner:A}
      at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:72) ~[forge-1.20.4-49.0.30-universal.jar!/:?] {re:classloading,pl:runtimedistcleaner:A}
      at net.minecraftforge.client.loading.ClientModLoader.startModLoading(ClientModLoader.java:80) ~[forge-1.20.4-49.0.30-universal.jar!/:?] {re:classloading,pl:runtimedistcleaner:A}
      at net.minecraftforge.client.loading.ClientModLoader.lambda$onResourceReload$2(ClientModLoader.java:63) ~[forge-1.20.4-49.0.30-universal.jar!/:?] {re:classloading,pl:runtimedistcleaner:A}
      at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:72) ~[forge-1.20.4-49.0.30-universal.jar!/:?] {re:classloading,pl:runtimedistcleaner:A}
      at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
      at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
      at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
      at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
      at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
      at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
      at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
      at com.electronwill.nightconfig.core.io.ParsingException.notEnoughData(ParsingException.java:22) ~[core-3.6.4.jar:?] {}
      at com.electronwill.nightconfig.core.io.ReaderInput.directReadChar(ReaderInput.java:36) ~[core-3.6.4.jar:?] {}
      at com.electronwill.nightconfig.core.io.AbstractInput.readChar(AbstractInput.java:49) ~[core-3.6.4.jar:?] {}
      at com.electronwill.nightconfig.core.io.AbstractInput.readCharsUntil(AbstractInput.java:123) ~[core-3.6.4.jar:?] {}
      at com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:166) ~[toml-3.6.4.jar:?] {}
      at com.electronwill.nightconfig.toml.TableParser.parseDottedKey(TableParser.java:145) ~[toml-3.6.4.jar:?] {}
      at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:55) ~[toml-3.6.4.jar:?] {}
      at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) ~[toml-3.6.4.jar:?] {}
      at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.4.jar:?] {}
      at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.4.jar:?] {}
      at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.4.jar:?] {}
      at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.4.jar:?] {}
      at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.4.jar:?] {}
      at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.4.jar:?] {}
      at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:43) ~[fmlcore-1.20.4-49.0.30.jar:?] {}
      ... 27 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: NONE
Stacktrace:
      at net.minecraftforge.fml.config.ConfigFileTypeHandler.lambda$reader$1(ConfigFileTypeHandler.java:47) ~[fmlcore-1.20.4-49.0.30.jar!/:?] {}
      at net.minecraftforge.fml.config.ConfigTracker.openConfig(ConfigTracker.java:60) ~[fmlcore-1.20.4-49.0.30.jar!/:?] {}
      at net.minecraftforge.fml.config.ConfigTracker.lambda$loadConfigs$1(ConfigTracker.java:50) ~[fmlcore-1.20.4-49.0.30.jar!/:?] {}
      at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {}
      at java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131) ~[?:?] {}
      at net.minecraftforge.fml.config.ConfigTracker.loadConfigs(ConfigTracker.java:50) ~[fmlcore-1.20.4-49.0.30.jar!/:?] {}
-- Overlay render details --
Details:
      Overlay name: net.minecraftforge.client.loading.ForgeLoadingOverlay
Stacktrace:
      at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:934) ~[forge-1.20.4-49.0.30-client.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
      at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1250) ~[forge-1.20.4-49.0.30-client.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
      at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:801) ~[forge-1.20.4-49.0.30-client.jar:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
      at net.minecraft.client.main.Main.main(Main.java:234) ~[forge-1.20.4-49.0.30-client.jar:?] {re:classloading,pl:runtimedistcleaner:A}
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
      at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
      at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:91) ~[fmlloader-1.20.4-49.0.30.jar:?] {}
      at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.lambda$makeService$0(CommonLaunchHandler.java:75) ~[fmlloader-1.20.4-49.0.30.jar:?] {}
      at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) ~[modlauncher-10.1.2.jar:?] {}
      at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:74) ~[modlauncher-10.1.2.jar:?] {}
      at cpw.mods.modlauncher.Launcher.run(Launcher.java:114) ~[modlauncher-10.1.2.jar:?] {}
      at cpw.mods.modlauncher.Launcher.main(Launcher.java:73) ~[modlauncher-10.1.2.jar:?] {}
      at cpw.mods.modlauncher.BootstrapEntry.main(BootstrapEntry.java:17) ~[modlauncher-10.1.2.jar:?] {}
      at net.minecraftforge.bootstrap.Bootstrap.moduleMain(Bootstrap.java:97) ~[bootstrap-2.0.0.jar!/:?] {}
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
      at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
      at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
      at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
      at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:48) ~[bootstrap-2.0.0.jar!/:?] {}
      at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:18) ~[bootstrap-2.0.0.jar!/:?] {}

-- Uptime --
Details:
      JVM uptime: 15.952s
      Wall uptime: 2.599s
      High-res time: 9.256s
      Client ticks: 10 ticks / 0.500s

-- Last reload --
Details:
      Reload number: 1
      Reload reason: initial
      Finished: No
      Packs: vanilla, mod_resources

-- System Details --
Details:
      Minecraft Version: 1.20.4
      Minecraft Version ID: 1.20.4
      Operating System: Windows 11 (amd64) version 10.0
      Java Version: 17.0.8, Microsoft
      Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
      Memory: 210563768 bytes (200 MiB) / 469762048 bytes (448 MiB) up to 2147483648 bytes (2048 MiB)
      CPUs: 16
      Processor Vendor: GenuineIntel
      Processor Name: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
      Identifier: Intel64 Family 6 Model 141 Stepping 1
      Microarchitecture: unknown
      Frequency (GHz): 2.30
      Number of physical packages: 1
      Number of physical CPUs: 8
      Number of logical CPUs: 16
      Graphics card #0 name: Intel(R) UHD Graphics
      Graphics card #0 vendor: Intel Corporation (0x8086)
      Graphics card #0 VRAM (MB): 1024.00
      Graphics card #0 deviceId: 0x9a60
      Graphics card #0 versionInfo: DriverVersion=31.0.101.1999
      Graphics card #1 name: NVIDIA GeForce RTX 3060 Laptop GPU
      Graphics card #1 vendor: NVIDIA (0x10de)
      Graphics card #1 VRAM (MB): 4095.00
      Graphics card #1 deviceId: 0x2560
      Graphics card #1 versionInfo: DriverVersion=31.0.15.2892
      Memory slot #0 capacity (MB): 8192.00
      Memory slot #0 clockSpeed (GHz): 3.20
      Memory slot #0 type: DDR4
      Memory slot #1 capacity (MB): 8192.00
      Memory slot #1 clockSpeed (GHz): 3.20
      Memory slot #1 type: DDR4
      Virtual memory max (MB): 27943.30
      Virtual memory used (MB): 14154.98
      Swap memory total (MB): 11776.00
      Swap memory used (MB): 90.13
      JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
      Launched Version: 1.20.4-forge-49.0.30
      Launcher name: minecraft-launcher
      Backend library: LWJGL version 3.3.2+13
      Backend API: Intel(R) UHD Graphics GL version 4.6.0 - Build 31.0.101.1999, Intel
      Window size: 854x480
      GL Caps: Using framebuffer using OpenGL 3.2
      GL debug messages:
      Using VBOs: Yes
      Is Modded: Definitely; Client brand changed to 'forge'
      Universe: 400921fb54442d18
      Type: Client (map_client.txt)
      Graphics mode: fast
      Render Distance: 12/12 chunks
      Resource Packs:
      Current Language: en_us
      Locale: en_US
      CPU: 16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
      ModLauncher: 10.1.2
      ModLauncher launch target: forge_client
      ModLauncher naming: srg
      ModLauncher services:
            / slf4jfixer PLUGINSERVICE
            / runtimedistcleaner PLUGINSERVICE
            / runtime_enum_extender PLUGINSERVICE
            / object_holder_definalize PLUGINSERVICE
            / capability_token_subclass PLUGINSERVICE
            / accesstransformer PLUGINSERVICE
            / eventbus PLUGINSERVICE
            / mixin PLUGINSERVICE
            / fml TRANSFORMATIONSERVICE
            / mixin TRANSFORMATIONSERVICE
      FML Language Providers:
            minecraft@1.0
            lowcodefml@49
            javafml@49.0.30
      Mod List:
            forge-1.20.4-49.0.30-client.jar                   |Minecraft                     |minecraft                     |1.20.4              |COMMON_SET|Manifest: NOSIGNATURE
            forge-1.20.4-49.0.30-universal.jar                |Forge                         |forge                         |49.0.30             |COMMON_SET|Manifest: NOSIGNATURE
      Crash Report UUID: 5380853b-d030-466a-8c5e-5c81ce00053c
      FML: 0.0
      Forge: net.minecraftforge:49.0.30

**Comment by Tiviacz1337** [comment]
Failed loading config file forge-client.toml of type CLIENT for modid forge
