### ISSUE TITLE
Backpack is not opening.

### ISSUE THREAD

**Issue by NothingTDo** [Tiviacz1337/Travelers-Backpack#899]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

Fabric 1.20.1-9.1.9 (Modpack: DarkRPG-7.8.8hf)

1. Describe the bug 

Cannot open backpack

2. Write steps to reproduce the bug

I cannot remember how it happened, it just so happened that my equipped backpack cannot be opened.

3. What is expected behaviour 

It should open backpack inventory upon pressing the set key bind on it.

4. Screenshots (If applicable)
https://youtu.be/9sCQR7T5ViM (video link)

**Comment by Tiviacz1337** [comment]
can you show me the console log?

**Comment by NothingTDo** [comment]
> can you show me the console log?

I apologize for the late reply. But I managed to get the server's console logs by the time the glitch happened to be.
If there is anything more you need, please let me know.
Thank you.

[2024-05-06-2.log.gz](https://github.com/Tiviacz1337/Travelers-Backpack/files/15231332/2024-05-06-2.log.gz)

**Comment by Tiviacz1337** [comment]
Seems like there's problem with Magistu armory item named PaviseItem
`[21:04:46] [Server thread/ERROR]: Error executing task on Server
java.lang.ClassCastException: class com.magistuarmory.item.PaviseItem cannot be cast to class net.minecraft.class_1746 (com.magistuarmory.item.PaviseItem and net.minecraft.class_1746 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3e57cd70)
	at com.magistuarmory.item.crafting.DecorationRemoveRecipe.takeApart(DecorationRemoveRecipe.java:135) ~[%5B1.20.1-fabric%5D-Epic-Knights-9.8.jar:?]
	at com.magistuarmory.item.crafting.DecorationRemoveRecipe.assemble(DecorationRemoveRecipe.java:80) ~[%5B1.20.1-fabric%5D-Epic-Knights-9.8.jar:?]
	at com.magistuarmory.item.crafting.DecorationRemoveRecipe.method_8116(DecorationRemoveRecipe.java:24) ~[%5B1.20.1-fabric%5D-Epic-Knights-9.8.jar:?]
	at com.tiviacz.travelersbackpack.inventory.screen.TravelersBackpackBaseScreenHandler.slotChangedCraftingGrid(TravelersBackpackBaseScreenHandler.java:213) ~[travelers-backpack-1.20.1-9.1.9.jar:?]
	at com.tiviacz.travelersbackpack.inventory.screen.TravelersBackpackBaseScreenHandler.method_7609(TravelersBackpackBaseScreenHandler.java:226) ~[travelers-backpack-1.20.1-9.1.9.jar:?]
	at com.tiviacz.travelersbackpack.inventory.screen.TravelersBackpackBaseScreenHandler.<init>(TravelersBackpackBaseScreenHandler.java:85) ~[travelers-backpack-1.20.1-9.1.9.jar:?]
	at com.tiviacz.travelersbackpack.inventory.screen.TravelersBackpackItemScreenHandler.<init>(TravelersBackpackItemScreenHandler.java:29) ~[travelers-backpack-1.20.1-9.1.9.jar:?]
	at com.tiviacz.travelersbackpack.inventory.TravelersBackpackInventory$1.createMenu(TravelersBackpackInventory.java:446) ~[travelers-backpack-1.20.1-9.1.9.jar:?]
	at net.minecraft.class_3222.method_17355(class_3222.java:1034) ~[server-intermediary.jar:?]
	at com.tiviacz.travelersbackpack.inventory.TravelersBackpackInventory.openHandledScreen(TravelersBackpackInventory.java:427) ~[travelers-backpack-1.20.1-9.1.9.jar:?]
	at com.tiviacz.travelersbackpack.init.ModNetwork.lambda$initServer$7(ModNetwork.java:161) ~[travelers-backpack-1.20.1-9.1.9.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]`

Probably needs to be reported to their devs

**Comment by NothingTDo** [comment]
> Seems like there's problem with Magistu armory item named PaviseItem `[21:04:46] [Server thread/ERROR]: Error executing task on Server java.lang.ClassCastException: class com.magistuarmory.item.PaviseItem cannot be cast to class net.minecraft.class_1746 (com.magistuarmory.item.PaviseItem and net.minecraft.class_1746 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @3e57cd70) at com.magistuarmory.item.crafting.DecorationRemoveRecipe.takeApart(DecorationRemoveRecipe.java:135) ~[%5B1.20.1-fabric%5D-Epic-Knights-9.8.jar:?] at com.magistuarmory.item.crafting.DecorationRemoveRecipe.assemble(DecorationRemoveRecipe.java:80) ~[%5B1.20.1-fabric%5D-Epic-Knights-9.8.jar:?] at com.magistuarmory.item.crafting.DecorationRemoveRecipe.method_8116(DecorationRemoveRecipe.java:24) ~[%5B1.20.1-fabric%5D-Epic-Knights-9.8.jar:?] at com.tiviacz.travelersbackpack.inventory.screen.TravelersBackpackBaseScreenHandler.slotChangedCraftingGrid(TravelersBackpackBaseScreenHandler.java:213) ~[travelers-backpack-1.20.1-9.1.9.jar:?] at com.tiviacz.travelersbackpack.inventory.screen.TravelersBackpackBaseScreenHandler.method_7609(TravelersBackpackBaseScreenHandler.java:226) ~[travelers-backpack-1.20.1-9.1.9.jar:?] at com.tiviacz.travelersbackpack.inventory.screen.TravelersBackpackBaseScreenHandler.<init>(TravelersBackpackBaseScreenHandler.java:85) ~[travelers-backpack-1.20.1-9.1.9.jar:?] at com.tiviacz.travelersbackpack.inventory.screen.TravelersBackpackItemScreenHandler.<init>(TravelersBackpackItemScreenHandler.java:29) ~[travelers-backpack-1.20.1-9.1.9.jar:?] at com.tiviacz.travelersbackpack.inventory.TravelersBackpackInventory$1.createMenu(TravelersBackpackInventory.java:446) ~[travelers-backpack-1.20.1-9.1.9.jar:?] at net.minecraft.class_3222.method_17355(class_3222.java:1034) ~[server-intermediary.jar:?] at com.tiviacz.travelersbackpack.inventory.TravelersBackpackInventory.openHandledScreen(TravelersBackpackInventory.java:427) ~[travelers-backpack-1.20.1-9.1.9.jar:?] at com.tiviacz.travelersbackpack.init.ModNetwork.lambda$initServer$7(ModNetwork.java:161) ~[travelers-backpack-1.20.1-9.1.9.jar:?] at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?] at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?] at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?] at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?] at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?] at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?] at java.lang.Thread.run(Thread.java:840) ~[?:?]`
> 
> Probably needs to be reported to their devs

Thank you so much for letting me know, I really appreciate the help you have done so far. 
I would fill out request a bug report to them and if you don't mind, may I send this thread to them as well so they would be able to know the current situation?

In the meanwhile, I would take a look around the conflicted mod so that I could get an idea of the said mod.
Thank you again!!

**Comment by Tiviacz1337** [comment]
Sure, go ahead, I think there's problem if said Pavise item is placed in Traveler's Backpack crafting grid - it might be reproduced but needs tests.
