### ISSUE TITLE
Crashing in 1.20.1

### ISSUE THREAD

**Issue by ponduzn** [Tiviacz1337/Travelers-Backpack#931]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
Fabric 0.15.7

1. Describe the bug 
Game crashes at random when using the backpack.

2. Write steps to reproduce the bug
open backpack, add or take out items, open, close bag, repeat until crashing.

Please let me know if i misunderstand the log, but i just saw it refers to travelers backpack mod and happens only when i do stuff with the backpack.

Error screen says : 
Game crashed
The game crashed whilst rendering screen 
Error: java.lang.IndexOutOfBoundsException: Index: 22, size: 19

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-06-22 18:02:00
Description: Rendering screen

java.lang.IndexOutOfBoundsException: Index: 22, Size: 19
	at java.base/java.util.ArrayList.rangeCheckForAdd(ArrayList.java:756)
	at java.base/java.util.ArrayList.add(ArrayList.java:481)
	at nourl.mythicmetals.abilities.Ability.lambda$addTooltip$0(Ability.java:97)
	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:34)
	at net.minecraft.class_1799.handler$ccj001$fabric-item-api-v1$getTooltip(class_1799.java:5611)
	at net.minecraft.class_1799.method_7950(class_1799.java:791)
	at net.minecraft.class_437.method_25408(class_437.java:225)
	at net.minecraft.class_465.method_51454(class_465.java:183)
	at net.minecraft.class_465.method_2380(class_465.java:178)
	at com.tiviacz.travelersbackpack.client.screen.TravelersBackpackHandledScreen.method_2380(TravelersBackpackHandledScreen.java:334)
	at com.tiviacz.travelersbackpack.client.screen.TravelersBackpackHandledScreen.method_25394(TravelersBackpackHandledScreen.java:328)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[crash-2024-06-22_18.02.00-client.txt](https://github.com/user-attachments/files/15937389/crash-2024-06-22_18.02.00-client.txt)

**Comment by Tiviacz1337** [comment]
It's probably mythic metals mod issue

**Comment by ponduzn** [comment]
Thanks!

**Comment by Tiviacz1337** [comment]
Closing, if needed reopen
