### ISSUE TITLE
Rendersystem called from wrong thread

### ISSUE THREAD

**Issue by ReneMuetti** [Tiviacz1337/Travelers-Backpack#964]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)
MC: 1.21
Fabric-Loader 0.16.0
Fabric: 0.100.7+1.21
Fabric Language Kotlin: 1.11.0+kotlin.2.0.0

1. Describe the bug 
```[07:59:06] [main/WARN]:
 Error loading class: net/minecraft/class_1886 (java.lang.ClassNotFoundException: net/minecraft/class_1886)
[07:59:06] [main/WARN]:
 @Inject(@At("INVOKE")) Shift.BY=2 on travelersbackpack.mixins.json:HandledScreenMixin from mod travelersbackpack::handler$dbm000$travelersbackpack$mouseClicked exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[07:59:06] [main/WARN]:
 Failed to get system info for GL Caps
java.lang.IllegalStateException: Rendersystem called from wrong thread
	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:140) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:135) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.getCapsString(RenderSystem.java:527) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:70) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2547) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2517) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:210) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]```

**Comment by ReneMuetti** [comment]
sorry -- wrong error-Report :(
